"""
Nursing career specializations / scope of practice after BSc Nursing.
Each entry: how to become, key skills, accepted countries, current trend.
Educational reference — check current requirements with the relevant nursing council.
"""

NURSING_SCOPES = [
    {
        "id": "informatics",
        "name": "Nurse Informatics Specialist",
        "emoji": "💻",
        "category": "Digital / Technology",
        "trend": "Very high demand — EMR adoption, AI in healthcare, telehealth.",
        "short_desc": "Bridges nursing practice with information technology — designing, implementing and optimizing electronic health records, clinical decision-support systems and healthcare data analytics.",
        "why_choose": [
            "Non-bedside role with excellent work-life balance.",
            "Rapidly growing field with strong compensation.",
            "Directly improves patient safety through better systems.",
        ],
        "how_to_become": [
            "Complete BSc Nursing + 1-2 years bedside clinical experience.",
            "Post-graduate certificate or MSc in Nursing Informatics / Health Informatics.",
            "International certifications: ANCC Informatics Nursing (RN-BC), CPHIMS, HL7 FHIR fundamentals.",
            "Learn: EHR systems (Epic, Cerner, Meditech), SQL, data analytics, healthcare data standards.",
        ],
        "core_skills": ["EHR configuration", "Clinical workflow analysis", "Data analytics", "Change management", "SQL / basic scripting"],
        "countries": [
            {"name": "USA", "note": "ANCC Informatics Nursing certification widely recognized. Epic / Cerner analyst roles."},
            {"name": "UK", "note": "NHS Digital roles. Faculty of Clinical Informatics (FCI) fellowship pathway."},
            {"name": "Canada", "note": "CNIA (Canadian Nursing Informatics Association) certification."},
            {"name": "Australia", "note": "HISA / ACHI courses. Digital health nurse consultant roles."},
            {"name": "UAE / KSA", "note": "Growing rapidly with hospital digital-transformation programs."},
        ],
        "typical_salary": "USD 75k-140k / year (USA); AED 15-25k / month (UAE)",
    },
    {
        "id": "educator",
        "name": "Nurse Educator",
        "emoji": "🎓",
        "category": "Education / Academia",
        "trend": "Persistent global shortage — universities and hospitals both hiring.",
        "short_desc": "Teaches and mentors student nurses and practicing staff — in universities, nursing colleges or hospital clinical-education departments.",
        "why_choose": [
            "Shape the next generation of nurses.",
            "Regular hours; academic calendar in university settings.",
            "Blend of teaching, research and clinical practice.",
        ],
        "how_to_become": [
            "BSc Nursing + minimum 2-5 years clinical experience (varies by country).",
            "MSc Nursing / MSc Nursing Education is the standard entry qualification.",
            "PhD required for senior academic posts.",
            "Certifications: CNE (Certified Nurse Educator) by NLN in the USA, PGCert in Higher Education in UK, ANMAC-approved course in Australia.",
        ],
        "core_skills": ["Curriculum design", "Simulation teaching (OSCE)", "Evidence-based practice", "Assessment & feedback", "Academic writing"],
        "countries": [
            {"name": "USA", "note": "CNE credential valued. MSN Education programs widely available."},
            {"name": "UK", "note": "NMC-registered teacher (NMC 2018) status. PGCHE required for lecturers."},
            {"name": "Canada", "note": "MN / MScN Education programs; nursing faculty shortage."},
            {"name": "Australia", "note": "Highly welcoming; ANMAC accreditation; academic nurse roles."},
            {"name": "UAE / KSA / Oman", "note": "High demand in HAAD/DOH & MOH-run colleges."},
        ],
        "typical_salary": "USD 75k-110k (USA university); AED 18-30k / month (Gulf)",
    },
    {
        "id": "quality",
        "name": "Quality & Patient Safety Nurse",
        "emoji": "🛡️",
        "category": "Quality / Governance",
        "trend": "Very high — Joint Commission (JCI), NABH, CQC accreditations everywhere.",
        "short_desc": "Ensures the hospital meets patient-safety standards and accreditation requirements. Runs audits, root-cause analyses and quality-improvement projects.",
        "why_choose": [
            "Hospital-wide impact on patient safety.",
            "Non-shift, non-bedside role.",
            "Fast-track to senior leadership.",
        ],
        "how_to_become": [
            "BSc Nursing + 3-5 years clinical experience (ICU / ER preferred).",
            "Post-graduate diploma or MSc in Hospital Administration / Healthcare Quality.",
            "International certifications: CPHQ (Certified Professional in Healthcare Quality) by NAHQ — the gold standard.",
            "Green-belt / Black-belt in Lean Six Sigma is a strong advantage.",
        ],
        "core_skills": ["Root-cause analysis", "Statistical process control", "Accreditation standards (JCI/NABH/CQC)", "PDSA cycles", "Clinical audit"],
        "countries": [
            {"name": "USA", "note": "CPHQ + The Joint Commission surveyors."},
            {"name": "UK", "note": "CQC inspectorate; NHS clinical-governance leads."},
            {"name": "UAE / KSA / Qatar", "note": "Explosive demand as new JCI-accredited hospitals open."},
            {"name": "India", "note": "NABH-implementation nurses in every major hospital."},
            {"name": "Singapore / Malaysia", "note": "MOH-driven quality programs."},
        ],
        "typical_salary": "USD 80k-130k (USA); AED 16-28k / month (UAE)",
    },
    {
        "id": "infection-control",
        "name": "Infection Prevention & Control Nurse",
        "emoji": "🧫",
        "category": "Public Health / Governance",
        "trend": "Elevated post-COVID; permanent role in every accredited hospital.",
        "short_desc": "Prevents healthcare-associated infections through surveillance, policy, staff education and outbreak management. Interfaces with microbiology, pharmacy and public-health authorities.",
        "why_choose": [
            "Highly respected specialty with clear career ladder.",
            "Non-shift, hospital-wide role.",
            "Global mobility — every accredited hospital needs an IPC nurse.",
        ],
        "how_to_become": [
            "BSc Nursing + 2-3 years clinical (ICU / medical wards preferred).",
            "Post-graduate diploma or MSc in Infection Control / Public Health.",
            "International certifications: CIC (Certification in Infection Control) by CBIC — the global standard.",
            "IPC Nurse (IPCN) short courses by CDC / WHO / IPCA (India).",
        ],
        "core_skills": ["Surveillance (CAUTI, CLABSI, SSI, VAP)", "Outbreak investigation", "Sterilization / disinfection", "Antimicrobial stewardship", "Hand hygiene programs"],
        "countries": [
            {"name": "USA", "note": "CIC-certified IPs are in every hospital; CDC guidelines."},
            {"name": "UK", "note": "IPC lead nurses per NHS trust; NICE guidelines."},
            {"name": "Canada", "note": "CIC certification + PIDAC standards."},
            {"name": "Australia", "note": "ACIPC credentialing pathway."},
            {"name": "UAE / KSA / Qatar", "note": "MoHAP / SCH mandatory role for JCI accreditation."},
        ],
        "typical_salary": "USD 70k-115k (USA); AED 15-25k / month (UAE)",
    },
    {
        "id": "tissue-viability",
        "name": "Tissue Viability / Wound Care Nurse",
        "emoji": "🩹",
        "category": "Clinical Specialty",
        "trend": "High and growing — ageing populations, diabetes, home-care.",
        "short_desc": "Specialist in prevention and management of pressure ulcers, diabetic foot ulcers, surgical wounds, stomas and complex chronic wounds. Runs consult-only or outpatient clinics.",
        "why_choose": [
            "Autonomous practice with clear patient outcomes.",
            "Outpatient / clinic hours in many settings.",
            "Portable skill set across all inpatient and community settings.",
        ],
        "how_to_become": [
            "BSc Nursing + 2-3 years clinical experience.",
            "Post-graduate certificate in Tissue Viability / Wound Care Nursing (universities offer 6-12 month programs).",
            "International certification: CWCN / CWON (WOCNCB, USA) — Certified Wound Care Nurse / Ostomy Nurse. In the UK: TVN qualification (RCN accredited).",
            "European: European Wound Management Association (EWMA) courses.",
        ],
        "core_skills": ["Wound-bed preparation (TIME framework)", "Compression therapy", "Negative-pressure wound therapy (NPWT)", "Stoma care", "Diabetic-foot assessment"],
        "countries": [
            {"name": "USA", "note": "CWCN / CWON — well-recognized; hospital and home-care roles."},
            {"name": "UK", "note": "Tissue Viability Nurse (TVN) — most NHS trusts have one."},
            {"name": "Australia", "note": "Wounds Australia certification."},
            {"name": "UAE / KSA", "note": "Growing role in wound-care clinics and long-term-care."},
            {"name": "Singapore", "note": "WOCN Society (Singapore Chapter)."},
        ],
        "typical_salary": "USD 75k-105k (USA); AED 14-22k / month (UAE)",
    },
    {
        "id": "crn",
        "name": "Clinical Research Nurse (CRN)",
        "emoji": "🔬",
        "category": "Research",
        "trend": "Booming — pharma trials, vaccine development, real-world evidence studies.",
        "short_desc": "Coordinates and delivers clinical trials — from consenting participants and administering study drugs to data collection, GCP compliance and regulatory reporting.",
        "why_choose": [
            "Contribute to medical science and drug development.",
            "Regular working hours; office-plus-clinic mix.",
            "Great pathway into research / regulatory affairs.",
        ],
        "how_to_become": [
            "BSc Nursing + clinical experience in the disease area (oncology / cardiology / neurology).",
            "Complete ICH-GCP (Good Clinical Practice) certification — free online.",
            "MSc in Clinical Research or Clinical Trials Management (optional but strong).",
            "International certifications: SoCRA CCRP or ACRP CCRC — recognized globally.",
        ],
        "core_skills": ["ICH-GCP compliance", "Informed consent", "Case Report Form (CRF) documentation", "Adverse-event reporting (SUSAR)", "Protocol adherence"],
        "countries": [
            {"name": "USA", "note": "NIH clinical centers; pharma sponsors; SoCRA CCRP."},
            {"name": "UK", "note": "NIHR Clinical Research Nurse pathway."},
            {"name": "India", "note": "Booming pharma / CRO industry; CDSCO regulations."},
            {"name": "Singapore / South Korea", "note": "Regional hubs for oncology trials."},
            {"name": "EU / Germany", "note": "AMG regulations; CRN roles at academic centers."},
        ],
        "typical_salary": "USD 70k-115k (USA); GBP 30-45k (UK); INR 8-18 LPA (India)",
    },
    {
        "id": "critical-care",
        "name": "ICU / Critical Care Nurse",
        "emoji": "🫀",
        "category": "Clinical Specialty",
        "trend": "Consistently high demand worldwide.",
        "short_desc": "Cares for critically ill patients on ventilators, vasopressors, CRRT and ECMO. High-acuity, high-autonomy bedside role.",
        "why_choose": [
            "Deep clinical expertise and high skill ceiling.",
            "Excellent pay differentials.",
            "Fast pathway to CRNA, NP or educator roles.",
        ],
        "how_to_become": [
            "BSc Nursing + 1-2 years med-surg experience.",
            "Post-basic diploma in Critical Care Nursing (PBCC) or MSc CCN.",
            "International certifications: CCRN (AACN, USA); ENB 100 (UK legacy) / QIS credentials; ACCCN in Australia.",
            "BLS + ACLS + PALS mandatory; ECMO and CRRT courses valued.",
        ],
        "core_skills": ["Mechanical ventilation", "Hemodynamic monitoring", "Vasoactive infusions", "ABG interpretation", "CRRT / ECMO support"],
        "countries": [
            {"name": "USA", "note": "CCRN highly valued; strong pay differential."},
            {"name": "UK", "note": "ICU nurse shortage — Band 5-7 roles."},
            {"name": "Australia", "note": "Postgraduate Cert / Dip in Critical Care."},
            {"name": "UAE / KSA / Qatar", "note": "Priority hire for JCI-accredited hospitals."},
            {"name": "Germany / Ireland", "note": "Post-registration critical-care programs."},
        ],
        "typical_salary": "USD 85k-140k (USA); AED 12-22k / month (UAE)",
    },
    {
        "id": "emergency",
        "name": "Emergency / Trauma Nurse",
        "emoji": "🚨",
        "category": "Clinical Specialty",
        "trend": "High — trauma-center expansion, air ambulance, tele-triage.",
        "short_desc": "First-line assessment, triage and resuscitation of patients arriving to the ED — from minor injuries to major trauma and cardiac arrest.",
        "why_choose": [
            "Fast-paced, variety-rich clinical practice.",
            "High autonomy in triage decisions.",
            "Direct pathway into flight / trauma / disaster nursing.",
        ],
        "how_to_become": [
            "BSc Nursing + med-surg / ICU experience.",
            "Triage courses (ATLS / TNCC / ENPC).",
            "Certifications: CEN (Certified Emergency Nurse) by BCEN, USA; ENB 199 legacy in UK.",
            "BLS + ACLS + PALS + TNCC mandatory.",
        ],
        "core_skills": ["Triage (ESI / Manchester)", "Trauma resuscitation", "Rapid-sequence intubation support", "Point-of-care ultrasound assist", "De-escalation of aggression"],
        "countries": [
            {"name": "USA", "note": "CEN + TNCC widely recognized."},
            {"name": "UK", "note": "Emergency Nurse Practitioner (ENP) pathway."},
            {"name": "Australia", "note": "CENA (College of Emergency Nursing Australasia)."},
            {"name": "UAE / KSA", "note": "Government-hospital ED roles."},
        ],
        "typical_salary": "USD 80k-130k (USA); AED 12-20k / month (UAE)",
    },
    {
        "id": "np",
        "name": "Nurse Practitioner (NP) / Advanced Practice",
        "emoji": "🩺",
        "category": "Advanced Practice",
        "trend": "Fastest-growing nursing role globally.",
        "short_desc": "Advanced-practice nurse with prescribing authority — assesses, diagnoses, treats and prescribes. Practices semi-autonomously in primary or specialty care.",
        "why_choose": [
            "Highest clinical autonomy short of a physician.",
            "Top-tier compensation.",
            "Enormous unmet demand in primary care.",
        ],
        "how_to_become": [
            "BSc Nursing → MSc Nursing / DNP (Doctor of Nursing Practice) — 2-4 years post-BSN.",
            "US: pass ANCC or AANP certification exam in specialty (FNP, AGNP, PNP, PMHNP, etc.).",
            "UK: MSc Advanced Clinical Practitioner (ACP) with prescribing rights (V300).",
            "Australia: NMBA-endorsed Nurse Practitioner (2-year MSN + 5000 clinical hours).",
        ],
        "core_skills": ["Differential diagnosis", "Physical assessment", "Independent prescribing", "Ordering & interpreting labs / imaging", "Chronic disease management"],
        "countries": [
            {"name": "USA", "note": "Full-practice authority in 27 states; DNP preferred entry."},
            {"name": "UK", "note": "ACP roles with V300 prescribing; walk-in centers."},
            {"name": "Canada", "note": "NP-PHC recognized in all provinces."},
            {"name": "Australia / NZ", "note": "Strong NP pathway; endorsed by NMBA / Nursing Council of NZ."},
            {"name": "UAE (Dubai)", "note": "DHA allows APN roles in select settings."},
        ],
        "typical_salary": "USD 115k-160k (USA); GBP 45-65k (UK)",
    },
    {
        "id": "neonatal",
        "name": "Neonatal / NICU Nurse",
        "emoji": "👶",
        "category": "Clinical Specialty",
        "trend": "High demand — increased premature births, high-risk pregnancies.",
        "short_desc": "Cares for premature and critically ill newborns — thermoregulation, feeding, ventilation, developmental care.",
        "why_choose": [
            "Deeply rewarding — see fragile babies grow and thrive.",
            "Highly specialized, well-compensated.",
            "Global mobility.",
        ],
        "how_to_become": [
            "BSc Nursing + pediatric / postnatal experience.",
            "PGCert / PGDip in Neonatal Nursing.",
            "Certifications: RNC-NIC (Neonatal Intensive Care Nursing) in USA; QIS 405 in UK; ANMAC-accredited course in Australia.",
            "NRP (Neonatal Resuscitation Program) mandatory.",
        ],
        "core_skills": ["Neonatal resuscitation (NRP)", "Ventilator / CPAP care", "Umbilical line care", "Kangaroo care", "Breastfeeding support"],
        "countries": [
            {"name": "USA", "note": "RNC-NIC + NRP; magnet-hospital NICUs."},
            {"name": "UK", "note": "QIS neonatal courses; ODN-level NICUs."},
            {"name": "Canada / Australia", "note": "Level-III NICU roles."},
            {"name": "UAE / KSA", "note": "Rapid growth in perinatal centers."},
        ],
        "typical_salary": "USD 85k-125k (USA); AED 12-20k / month (UAE)",
    },
    {
        "id": "oncology",
        "name": "Oncology Nurse",
        "emoji": "🎗️",
        "category": "Clinical Specialty",
        "trend": "Very high — cancer prevalence rising globally.",
        "short_desc": "Delivers chemotherapy, immunotherapy and radiation-oncology care; supports patients through diagnosis, treatment and survivorship or end-of-life.",
        "why_choose": [
            "Profoundly meaningful patient relationships.",
            "Skill ceiling is high — clinical trials, precision medicine.",
            "Excellent research and NP pipeline.",
        ],
        "how_to_become": [
            "BSc Nursing + 2 years clinical.",
            "Chemotherapy administration certificate (ONS / SIOP courses).",
            "International certifications: OCN (Oncology Certified Nurse) by ONCC in USA; UKONS competency framework in UK.",
        ],
        "core_skills": ["Safe chemo handling", "Vascular access (PICC, ports)", "Extravasation management", "Symptom control", "Psychosocial support"],
        "countries": [
            {"name": "USA", "note": "OCN + BMT-CN highly regarded."},
            {"name": "UK", "note": "UKONS competency; chemo nurses in every trust."},
            {"name": "India", "note": "Growing cancer-centers network."},
            {"name": "UAE / KSA / Qatar", "note": "New cancer institutes hiring aggressively."},
        ],
        "typical_salary": "USD 80k-120k (USA); AED 13-22k / month (UAE)",
    },
    {
        "id": "dialysis",
        "name": "Dialysis / Renal Nurse",
        "emoji": "🩸",
        "category": "Clinical Specialty",
        "trend": "High — diabetes and CKD driving demand.",
        "short_desc": "Specializes in hemodialysis, peritoneal dialysis and CRRT for renal-failure patients; often in dedicated units or outpatient centers.",
        "why_choose": [
            "Structured shifts (often no nights).",
            "Long-term patient relationships.",
            "Portable skill set across the world.",
        ],
        "how_to_become": [
            "BSc Nursing + medical / ICU experience.",
            "Renal-nursing course (6-12 months) by the local dialysis provider (Fresenius, DaVita, B. Braun).",
            "Certifications: CNN / CNN-NP (Nephrology Nursing Certification Board, USA); QIS in UK.",
        ],
        "core_skills": ["Vascular access care (AV fistula)", "Hemodialysis machine operation", "Water treatment / RO", "PD training", "CRRT in ICU"],
        "countries": [
            {"name": "USA", "note": "CNN certification widely recognized."},
            {"name": "UAE / KSA / Kuwait", "note": "Huge demand; free-standing dialysis chains."},
            {"name": "UK", "note": "Renal-specialist nurse pathway."},
            {"name": "Singapore", "note": "NKF (National Kidney Foundation) network."},
        ],
        "typical_salary": "USD 70k-105k (USA); AED 12-18k / month (UAE)",
    },
    {
        "id": "or",
        "name": "OR / Perioperative Nurse",
        "emoji": "🔪",
        "category": "Clinical Specialty",
        "trend": "Stable high demand — surgical volumes rising.",
        "short_desc": "Scrub / circulating / anesthesia-assist nurse in the operating room, plus pre-op holding and PACU roles.",
        "why_choose": [
            "Structured environment, no long-term patient follow-up.",
            "Fast pathway into RNFA (RN First Assistant).",
            "Global mobility, excellent pay differentials.",
        ],
        "how_to_become": [
            "BSc Nursing + med-surg experience.",
            "Perioperative-nursing course by AORN (USA) or NATN (UK).",
            "Certifications: CNOR (Certified Perioperative Nurse) by CCI, USA.",
            "PALS + ACLS.",
        ],
        "core_skills": ["Aseptic technique", "Instrument counting", "Positioning & padding", "Electrosurgery safety", "Time-out protocols"],
        "countries": [
            {"name": "USA", "note": "CNOR standard credential."},
            {"name": "UK", "note": "ODP overlaps; theater-nurse Bands 5-6."},
            {"name": "Australia", "note": "ACORN standards."},
            {"name": "UAE / KSA", "note": "Priority hire for surgical hospitals."},
        ],
        "typical_salary": "USD 80k-120k (USA); AED 12-20k / month (UAE)",
    },
    {
        "id": "mental-health",
        "name": "Psychiatric / Mental Health Nurse",
        "emoji": "🧠",
        "category": "Clinical Specialty",
        "trend": "Rapidly rising — mental-health crisis, tele-psychiatry.",
        "short_desc": "Assesses, treats and supports patients with mental-health conditions across inpatient, outpatient, addiction and community-mental-health settings.",
        "why_choose": [
            "Deep therapeutic relationships.",
            "Growing role in schools, prisons and workplaces.",
            "Pathway to PMHNP (Psychiatric Nurse Practitioner).",
        ],
        "how_to_become": [
            "BSc Nursing + mental-health rotation.",
            "PG Diploma / MSc in Mental Health Nursing.",
            "Certifications: PMH-BC (Psychiatric-Mental Health Nurse) by ANCC in USA; RMN pathway in UK.",
        ],
        "core_skills": ["Mental-status exam", "De-escalation techniques", "Cognitive-behavioral techniques", "Suicide-risk assessment", "Psychopharmacology"],
        "countries": [
            {"name": "USA", "note": "PMHNP fastest-growing NP specialty."},
            {"name": "UK", "note": "RMN is a distinct registration from adult nurse."},
            {"name": "Australia", "note": "Credentialed Mental Health Nurse (CMHN)."},
            {"name": "Ireland / Canada", "note": "Separate mental-health nursing registers."},
        ],
        "typical_salary": "USD 80k-115k (USA); GBP 32-45k (UK)",
    },
    {
        "id": "midwife",
        "name": "Midwife / Obstetric Nurse",
        "emoji": "🤱",
        "category": "Clinical Specialty",
        "trend": "Persistent high demand.",
        "short_desc": "Provides antenatal, intrapartum and postnatal care to women and newborns — hospital, birthing-center or community based.",
        "why_choose": [
            "Autonomous practice model in many countries.",
            "Deeply rewarding work.",
            "Portable skill across the world.",
        ],
        "how_to_become": [
            "BSc Nursing + PB (Post-basic) BSc Midwifery — or BSc Midwifery direct-entry in UK / Australia.",
            "Certifications: RM (Registered Midwife) via country nursing council.",
            "USA: CNM (Certified Nurse Midwife) via ACNM — requires MSN.",
        ],
        "core_skills": ["Antenatal assessment", "Fetal monitoring (CTG)", "Normal & assisted delivery", "Immediate newborn care", "Perinatal mental-health"],
        "countries": [
            {"name": "UK", "note": "3-year direct-entry BSc Midwifery — NMC registration."},
            {"name": "Australia / NZ", "note": "BMid direct-entry; independent practice."},
            {"name": "USA", "note": "CNM via ACNM — MSN required."},
            {"name": "Ireland / Canada", "note": "Registered Midwife pathway."},
            {"name": "India / Africa", "note": "ANM / RM roles in maternal-health programs."},
        ],
        "typical_salary": "USD 90k-125k (USA CNM); GBP 30-45k (UK)",
    },
    {
        "id": "public-health",
        "name": "Public Health / Community Nurse",
        "emoji": "🌍",
        "category": "Public Health",
        "trend": "Elevated post-COVID; strong in home-care.",
        "short_desc": "Delivers health-promotion, immunization, screening, home visits and outbreak response — usually employed by government or NGO health services.",
        "why_choose": [
            "Population-level impact.",
            "Regular hours, no shifts.",
            "Pathway into WHO / UNICEF / health-policy roles.",
        ],
        "how_to_become": [
            "BSc Nursing + community rotation.",
            "PG Diploma / MPH (Master of Public Health) recommended.",
            "Certifications: SCPHN in UK; PHN in USA (varies by state).",
        ],
        "core_skills": ["Epidemiology basics", "Health-education", "Home visiting", "Immunization programs", "Contact tracing"],
        "countries": [
            {"name": "USA", "note": "Public-health nurse credentials via ANCC."},
            {"name": "UK", "note": "SCPHN (Specialist Community Public Health Nurse) — health visitor / school nurse."},
            {"name": "Canada / Australia", "note": "Community-health nurse roles."},
            {"name": "Africa / South Asia", "note": "WHO, UNICEF, national immunization programs."},
        ],
        "typical_salary": "USD 65k-90k (USA); GBP 30-42k (UK)",
    },
]

CATEGORIES_ORDER = [
    "Digital / Technology",
    "Advanced Practice",
    "Clinical Specialty",
    "Quality / Governance",
    "Public Health / Governance",
    "Public Health",
    "Research",
    "Education / Academia",
]

# ---- Current global trends in nursing ----
NURSING_TRENDS = [
    {
        "id": "tele-nursing",
        "title": "Tele-nursing & virtual care",
        "emoji": "📱",
        "summary": "Video-based triage, remote monitoring and chronic-disease management. Every major insurer now covers tele-nursing services.",
        "what_to_study": ["Tele-triage protocols", "Remote-patient-monitoring (RPM) platforms", "Digital communication skills"],
    },
    {
        "id": "ai-nursing",
        "title": "AI & clinical decision support",
        "emoji": "🤖",
        "summary": "AI-driven early-warning scores (sepsis, deterioration), image analysis and documentation copilots are becoming standard.",
        "what_to_study": ["AI literacy", "Clinical decision-support workflows", "Data ethics & bias", "Nurse Informatics fundamentals"],
    },
    {
        "id": "genomics",
        "title": "Genomics & precision medicine",
        "emoji": "🧬",
        "summary": "Nurses are increasingly involved in explaining genetic tests, targeted-therapy administration and pharmacogenomics.",
        "what_to_study": ["Genomic Nursing (ISONG)", "Pharmacogenomics", "Family history assessment"],
    },
    {
        "id": "climate-health",
        "title": "Climate & planetary health",
        "emoji": "🌱",
        "summary": "Extreme heat, air pollution, vector-borne disease — climate impacts nursing. WHO now emphasises 'climate-smart' nursing.",
        "what_to_study": ["Environmental epidemiology", "Sustainable clinical practice", "Disaster nursing"],
    },
    {
        "id": "mental-health-crisis",
        "title": "Mental-health integration",
        "emoji": "💚",
        "summary": "Behavioural health is now integrated into every specialty; PMH nurses and NPs are the fastest-growing group in the West.",
        "what_to_study": ["Screening tools (PHQ-9, GAD-7, C-SSRS)", "Trauma-informed care", "Motivational interviewing"],
    },
    {
        "id": "global-mobility",
        "title": "Global nurse mobility",
        "emoji": "✈️",
        "summary": "USA, UK, Germany, Australia, Canada, UAE and KSA are actively recruiting internationally-educated nurses through fast-track pathways.",
        "what_to_study": ["IELTS / OET (English proficiency)", "NCLEX-RN / OSCE / Prometric prep", "Country-specific licensing paperwork"],
    },
    {
        "id": "advanced-practice",
        "title": "Rise of Advanced Practice",
        "emoji": "🎓",
        "summary": "Nurse Practitioners, Anesthetists and Midwives are practicing more independently in many countries — driving nursing to master's / doctoral level entry.",
        "what_to_study": ["MSc / DNP programs", "Advanced physical assessment", "Prescribing pharmacology"],
    },
    {
        "id": "prevention",
        "title": "Prevention & value-based care",
        "emoji": "🛡️",
        "summary": "Healthcare payment models are shifting from fee-for-service to value-based care — nurses lead chronic-disease-management programs.",
        "what_to_study": ["Care coordination", "Chronic-care management", "Population-health metrics"],
    },
]
