"""
Pediatric emergency drug + Broselow cart data.
All doses are educational reference values based on standard published pediatric guidelines
(APLS / AHA PALS / BNF-C / RCH Melbourne). ALWAYS verify against local institutional
protocol and prescriber orders before administering to a patient.
"""
from __future__ import annotations

# ---- Broselow tape colour zones (weight-based) ----
# Each zone contains resuscitation-critical parameters at the *mid-weight* for that band.
# Nurses should still calculate exact mg/kg for their patient's actual weight.
BROSELOW_ZONES = [
    {
        "color": "Grey",   "hex": "#94A3B8",
        "weight_kg_min": 3, "weight_kg_max": 5, "age_approx": "0-3 months",
        "et_tube_uncuffed": "3.5", "et_tube_cuffed": "3.0",
        "et_tube_depth_cm": "10-11", "lma_size": "1",
        "adrenaline_iv_mg": "0.03-0.05",    "adrenaline_iv_ml_1_10k": "0.3-0.5",
        "adrenaline_im_1_1k_mg": "0.03-0.05","adrenaline_ett_mg": "0.3-0.5",
        "atropine_mg": "0.1",               "amiodarone_mg": "15-25",
        "adenosine_first_mg": "0.3-0.5",    "adenosine_second_mg": "0.6-1",
        "defib_j": "6-20", "cardiovert_j": "2-5",
        "fluid_bolus_ml": "60-100", "d10w_ml": "15-25",
        "naloxone_mg": "0.3-0.5", "midazolam_mg": "0.3-0.5",
        "diazepam_mg": "0.6-1", "fentanyl_mcg": "3-5",
        "ketamine_iv_mg": "3-10", "paracetamol_pr_mg": "45-75",
    },
    {
        "color": "Pink",   "hex": "#F9A8D4",
        "weight_kg_min": 6, "weight_kg_max": 7, "age_approx": "3-6 months",
        "et_tube_uncuffed": "3.5", "et_tube_cuffed": "3.0",
        "et_tube_depth_cm": "11-12", "lma_size": "1.5",
        "adrenaline_iv_mg": "0.06-0.07",    "adrenaline_iv_ml_1_10k": "0.6-0.7",
        "adrenaline_im_1_1k_mg": "0.06-0.07","adrenaline_ett_mg": "0.6-0.7",
        "atropine_mg": "0.12-0.14", "amiodarone_mg": "30-35",
        "adenosine_first_mg": "0.6-0.7", "adenosine_second_mg": "1.2-1.4",
        "defib_j": "12-28", "cardiovert_j": "3-7",
        "fluid_bolus_ml": "120-140", "d10w_ml": "30-35",
        "naloxone_mg": "0.6-0.7", "midazolam_mg": "0.6-0.7",
        "diazepam_mg": "1.2-3.5", "fentanyl_mcg": "6-14",
        "ketamine_iv_mg": "6-14", "paracetamol_pr_mg": "90-105",
    },
    {
        "color": "Red",    "hex": "#EF4444",
        "weight_kg_min": 8, "weight_kg_max": 9, "age_approx": "6-12 months",
        "et_tube_uncuffed": "4.0", "et_tube_cuffed": "3.5",
        "et_tube_depth_cm": "12-13", "lma_size": "1.5-2",
        "adrenaline_iv_mg": "0.08-0.09", "adrenaline_iv_ml_1_10k": "0.8-0.9",
        "adrenaline_im_1_1k_mg": "0.08-0.09", "adrenaline_ett_mg": "0.8-0.9",
        "atropine_mg": "0.16-0.18", "amiodarone_mg": "40-45",
        "adenosine_first_mg": "0.8-0.9", "adenosine_second_mg": "1.6-1.8",
        "defib_j": "16-36", "cardiovert_j": "4-9",
        "fluid_bolus_ml": "160-180", "d10w_ml": "40-45",
        "naloxone_mg": "0.8-0.9", "midazolam_mg": "0.8-0.9",
        "diazepam_mg": "1.6-4.5", "fentanyl_mcg": "8-18",
        "ketamine_iv_mg": "8-18", "paracetamol_pr_mg": "120-135",
    },
    {
        "color": "Purple", "hex": "#8B5CF6",
        "weight_kg_min": 10, "weight_kg_max": 11, "age_approx": "12-24 months",
        "et_tube_uncuffed": "4.0", "et_tube_cuffed": "3.5",
        "et_tube_depth_cm": "12-13", "lma_size": "2",
        "adrenaline_iv_mg": "0.1-0.11", "adrenaline_iv_ml_1_10k": "1.0-1.1",
        "adrenaline_im_1_1k_mg": "0.1-0.11", "adrenaline_ett_mg": "1.0-1.1",
        "atropine_mg": "0.2-0.22", "amiodarone_mg": "50-55",
        "adenosine_first_mg": "1.0-1.1", "adenosine_second_mg": "2.0-2.2",
        "defib_j": "20-44", "cardiovert_j": "5-11",
        "fluid_bolus_ml": "200-220", "d10w_ml": "50-55",
        "naloxone_mg": "1.0-1.1", "midazolam_mg": "1.0-1.1",
        "diazepam_mg": "2.0-5.5", "fentanyl_mcg": "10-22",
        "ketamine_iv_mg": "10-22", "paracetamol_pr_mg": "150-165",
    },
    {
        "color": "Yellow", "hex": "#FBBF24",
        "weight_kg_min": 12, "weight_kg_max": 14, "age_approx": "2-3 years",
        "et_tube_uncuffed": "4.5", "et_tube_cuffed": "4.0",
        "et_tube_depth_cm": "13-14", "lma_size": "2",
        "adrenaline_iv_mg": "0.12-0.14", "adrenaline_iv_ml_1_10k": "1.2-1.4",
        "adrenaline_im_1_1k_mg": "0.12-0.14", "adrenaline_ett_mg": "1.2-1.4",
        "atropine_mg": "0.24-0.28", "amiodarone_mg": "60-70",
        "adenosine_first_mg": "1.2-1.4", "adenosine_second_mg": "2.4-2.8",
        "defib_j": "24-56", "cardiovert_j": "6-14",
        "fluid_bolus_ml": "240-280", "d10w_ml": "60-70",
        "naloxone_mg": "1.2-1.4", "midazolam_mg": "1.2-1.4",
        "diazepam_mg": "2.4-7", "fentanyl_mcg": "12-28",
        "ketamine_iv_mg": "12-28", "paracetamol_pr_mg": "180-210",
    },
    {
        "color": "White",  "hex": "#F1F5F9",
        "weight_kg_min": 15, "weight_kg_max": 18, "age_approx": "3-5 years",
        "et_tube_uncuffed": "5.0", "et_tube_cuffed": "4.5",
        "et_tube_depth_cm": "14-15", "lma_size": "2-2.5",
        "adrenaline_iv_mg": "0.15-0.18", "adrenaline_iv_ml_1_10k": "1.5-1.8",
        "adrenaline_im_1_1k_mg": "0.15-0.18", "adrenaline_ett_mg": "1.5-1.8",
        "atropine_mg": "0.3-0.36", "amiodarone_mg": "75-90",
        "adenosine_first_mg": "1.5-1.8", "adenosine_second_mg": "3.0-3.6",
        "defib_j": "30-72", "cardiovert_j": "7-18",
        "fluid_bolus_ml": "300-360", "d10w_ml": "75-90",
        "naloxone_mg": "1.5-1.8", "midazolam_mg": "1.5-1.8",
        "diazepam_mg": "3-9", "fentanyl_mcg": "15-36",
        "ketamine_iv_mg": "15-36", "paracetamol_pr_mg": "225-270",
    },
    {
        "color": "Blue",   "hex": "#3B82F6",
        "weight_kg_min": 19, "weight_kg_max": 22, "age_approx": "5-7 years",
        "et_tube_uncuffed": "5.5", "et_tube_cuffed": "5.0",
        "et_tube_depth_cm": "15-16", "lma_size": "2.5",
        "adrenaline_iv_mg": "0.19-0.22", "adrenaline_iv_ml_1_10k": "1.9-2.2",
        "adrenaline_im_1_1k_mg": "0.19-0.22", "adrenaline_ett_mg": "1.9-2.2",
        "atropine_mg": "0.38-0.44", "amiodarone_mg": "95-110",
        "adenosine_first_mg": "1.9-2.2", "adenosine_second_mg": "3.8-4.4",
        "defib_j": "38-88", "cardiovert_j": "9-22",
        "fluid_bolus_ml": "380-440", "d10w_ml": "95-110",
        "naloxone_mg": "1.9-2.2", "midazolam_mg": "1.9-2.2",
        "diazepam_mg": "3.8-10", "fentanyl_mcg": "19-44",
        "ketamine_iv_mg": "19-44", "paracetamol_pr_mg": "285-330",
    },
    {
        "color": "Orange", "hex": "#F97316",
        "weight_kg_min": 24, "weight_kg_max": 28, "age_approx": "7-9 years",
        "et_tube_uncuffed": "6.0", "et_tube_cuffed": "5.5",
        "et_tube_depth_cm": "16-17", "lma_size": "3",
        "adrenaline_iv_mg": "0.24-0.28", "adrenaline_iv_ml_1_10k": "2.4-2.8",
        "adrenaline_im_1_1k_mg": "0.24-0.28", "adrenaline_ett_mg": "2.4-2.8",
        "atropine_mg": "0.48-0.56", "amiodarone_mg": "120-140",
        "adenosine_first_mg": "2.4-2.8", "adenosine_second_mg": "4.8-5.6",
        "defib_j": "48-112", "cardiovert_j": "12-28",
        "fluid_bolus_ml": "480-560", "d10w_ml": "120-140",
        "naloxone_mg": "2.4-2.8", "midazolam_mg": "2-5",
        "diazepam_mg": "4.8-10", "fentanyl_mcg": "24-56",
        "ketamine_iv_mg": "24-56", "paracetamol_pr_mg": "360-420",
    },
    {
        "color": "Green",  "hex": "#10B981",
        "weight_kg_min": 30, "weight_kg_max": 36, "age_approx": "9-11 years",
        "et_tube_uncuffed": "6.5", "et_tube_cuffed": "6.0",
        "et_tube_depth_cm": "17-18", "lma_size": "3",
        "adrenaline_iv_mg": "0.3-0.36", "adrenaline_iv_ml_1_10k": "3.0-3.6",
        "adrenaline_im_1_1k_mg": "0.3-0.5", "adrenaline_ett_mg": "3.0-3.6",
        "atropine_mg": "0.6", "amiodarone_mg": "150-180",
        "adenosine_first_mg": "3.0-3.6", "adenosine_second_mg": "6.0-7.2",
        "defib_j": "60-144", "cardiovert_j": "15-36",
        "fluid_bolus_ml": "600-720", "d10w_ml": "150-180",
        "naloxone_mg": "2", "midazolam_mg": "2-5",
        "diazepam_mg": "6-10", "fentanyl_mcg": "30-72",
        "ketamine_iv_mg": "30-72", "paracetamol_pr_mg": "450-540",
    },
]


# ---- Pediatric weight-based drug library ----
# Fields:
#   id, name, category, route, dose_per_kg_mg (or _mcg/_units), dose_range,
#   frequency, max_single_dose_mg, indication, notes, common_concentration
PEDIATRIC_DRUGS = [
    # ---- Emergency / resuscitation ----
    {"id": "adr-iv",  "name": "Adrenaline (Epinephrine) IV/IO", "category": "Emergency", "route": "IV/IO",
     "dose_mg_per_kg": 0.01, "dose_range": "0.01 mg/kg (1:10,000)", "frequency": "Every 3-5 min",
     "max_single_dose_mg": 1.0, "indication": "Cardiac arrest, bradycardia with poor perfusion",
     "common_concentration_mg_per_ml": 0.1, "notes": "Use 1:10,000 (0.1 mg/mL). Flush with 5-10 mL NS."},
    {"id": "adr-im",  "name": "Adrenaline (Epinephrine) IM", "category": "Emergency", "route": "IM",
     "dose_mg_per_kg": 0.01, "dose_range": "0.01 mg/kg (1:1000)", "frequency": "Every 5-15 min",
     "max_single_dose_mg": 0.5, "indication": "Anaphylaxis",
     "common_concentration_mg_per_ml": 1.0, "notes": "Use 1:1000 (1 mg/mL). Anterolateral thigh preferred."},
    {"id": "atropine","name": "Atropine", "category": "Emergency", "route": "IV/IO",
     "dose_mg_per_kg": 0.02, "dose_range": "0.02 mg/kg",  "frequency": "May repeat once in 5 min",
     "max_single_dose_mg": 0.5, "indication": "Symptomatic bradycardia, organophosphate poisoning",
     "common_concentration_mg_per_ml": 0.5, "notes": "Minimum single dose 0.1 mg."},
    {"id": "amio",    "name": "Amiodarone", "category": "Emergency", "route": "IV/IO",
     "dose_mg_per_kg": 5, "dose_range": "5 mg/kg (bolus)", "frequency": "May repeat up to 15 mg/kg",
     "max_single_dose_mg": 300, "indication": "Shock-refractory VF/pVT, SVT",
     "common_concentration_mg_per_ml": 50, "notes": "Give as slow bolus in pulseless arrest."},
    {"id": "adeno",   "name": "Adenosine", "category": "Emergency", "route": "IV/IO",
     "dose_mg_per_kg": 0.1, "dose_range": "0.1 mg/kg (1st), 0.2 mg/kg (2nd)", "frequency": "Rapid bolus + flush",
     "max_single_dose_mg": 6, "indication": "SVT (narrow-complex tachycardia)",
     "common_concentration_mg_per_ml": 3, "notes": "Give rapid IV push closest to heart, flush 5-10 mL NS."},
    {"id": "nalox",   "name": "Naloxone", "category": "Emergency", "route": "IV/IM/IO",
     "dose_mg_per_kg": 0.1, "dose_range": "0.1 mg/kg", "frequency": "Repeat every 2-3 min",
     "max_single_dose_mg": 2, "indication": "Opioid reversal",
     "common_concentration_mg_per_ml": 0.4, "notes": "Short half-life; repeat doses often needed."},

    # ---- Sedation / analgesia ----
    {"id": "midaz",   "name": "Midazolam IV", "category": "Sedation", "route": "IV",
     "dose_mg_per_kg": 0.1, "dose_range": "0.05-0.2 mg/kg", "frequency": "Single dose or infusion",
     "max_single_dose_mg": 5, "indication": "Procedural sedation, seizure",
     "common_concentration_mg_per_ml": 1, "notes": "Watch for respiratory depression."},
    {"id": "ket",     "name": "Ketamine IV", "category": "Sedation", "route": "IV",
     "dose_mg_per_kg": 1, "dose_range": "1-2 mg/kg", "frequency": "Titrate",
     "max_single_dose_mg": 100, "indication": "Procedural sedation, RSI",
     "common_concentration_mg_per_ml": 10, "notes": "Preserves airway reflexes; may cause emergence phenomena."},
    {"id": "fent",    "name": "Fentanyl", "category": "Analgesia", "route": "IV",
     "dose_mcg_per_kg": 1, "dose_range": "1-2 mcg/kg",  "frequency": "Every 30-60 min",
     "max_single_dose_mcg": 100, "indication": "Analgesia, RSI",
     "common_concentration_mcg_per_ml": 50, "notes": "Rapid onset. Give slowly to avoid chest-wall rigidity."},
    {"id": "morph",   "name": "Morphine", "category": "Analgesia", "route": "IV",
     "dose_mg_per_kg": 0.1, "dose_range": "0.05-0.2 mg/kg", "frequency": "Every 3-4 h",
     "max_single_dose_mg": 10, "indication": "Moderate-severe pain",
     "common_concentration_mg_per_ml": 1, "notes": "Dilute for slow push over 5 min."},
    {"id": "para-po", "name": "Paracetamol PO/PR", "category": "Analgesia", "route": "PO/PR",
     "dose_mg_per_kg": 15, "dose_range": "10-15 mg/kg", "frequency": "Every 4-6 h (max 60 mg/kg/day)",
     "max_single_dose_mg": 1000, "indication": "Fever, mild pain",
     "common_concentration_mg_per_ml": 24, "notes": "Do not exceed 4 g/day in older children."},
    {"id": "ibu",     "name": "Ibuprofen PO", "category": "Analgesia", "route": "PO",
     "dose_mg_per_kg": 10, "dose_range": "5-10 mg/kg", "frequency": "Every 6-8 h",
     "max_single_dose_mg": 400, "indication": "Fever, inflammatory pain",
     "common_concentration_mg_per_ml": 20, "notes": "Avoid in dehydration, renal impairment, <3 months."},

    # ---- Antibiotics ----
    {"id": "amox",    "name": "Amoxicillin PO", "category": "Antibiotic", "route": "PO",
     "dose_mg_per_kg": 25, "dose_range": "25-50 mg/kg/dose", "frequency": "Every 8 h",
     "max_single_dose_mg": 1000, "indication": "Otitis, pneumonia, pharyngitis",
     "common_concentration_mg_per_ml": 50, "notes": "Higher end for severe infection."},
    {"id": "ceftri",  "name": "Ceftriaxone", "category": "Antibiotic", "route": "IV/IM",
     "dose_mg_per_kg": 50, "dose_range": "50-100 mg/kg/day", "frequency": "Once daily",
     "max_single_dose_mg": 2000, "indication": "Meningitis, sepsis, pneumonia",
     "common_concentration_mg_per_ml": 100, "notes": "Reconstitute per vial. Slow push over 2-4 min IV."},
    {"id": "cefotax", "name": "Cefotaxime", "category": "Antibiotic", "route": "IV",
     "dose_mg_per_kg": 50, "dose_range": "50 mg/kg/dose", "frequency": "Every 6-8 h",
     "max_single_dose_mg": 2000, "indication": "Sepsis, meningitis (neonates)",
     "common_concentration_mg_per_ml": 100, "notes": ""},
    {"id": "gent",    "name": "Gentamicin", "category": "Antibiotic", "route": "IV",
     "dose_mg_per_kg": 5, "dose_range": "5-7.5 mg/kg once daily", "frequency": "Once daily",
     "max_single_dose_mg": 400, "indication": "Gram-negative sepsis",
     "common_concentration_mg_per_ml": 10, "notes": "Monitor levels & renal function."},
    {"id": "vanc",    "name": "Vancomycin", "category": "Antibiotic", "route": "IV",
     "dose_mg_per_kg": 15, "dose_range": "15 mg/kg/dose", "frequency": "Every 6 h",
     "max_single_dose_mg": 1000, "indication": "MRSA, resistant Gram-positive",
     "common_concentration_mg_per_ml": 5, "notes": "Infuse over ≥60 min. Monitor trough level."},
    {"id": "metro",   "name": "Metronidazole", "category": "Antibiotic", "route": "IV/PO",
     "dose_mg_per_kg": 7.5, "dose_range": "7.5 mg/kg/dose", "frequency": "Every 8 h",
     "max_single_dose_mg": 500, "indication": "Anaerobic infection, C. difficile",
     "common_concentration_mg_per_ml": 5, "notes": ""},
    {"id": "mero",    "name": "Meropenem", "category": "Antibiotic", "route": "IV",
     "dose_mg_per_kg": 20, "dose_range": "20-40 mg/kg/dose", "frequency": "Every 8 h",
     "max_single_dose_mg": 2000, "indication": "Severe / resistant sepsis, meningitis",
     "common_concentration_mg_per_ml": 50, "notes": "Higher dose (40 mg/kg) for meningitis."},
    {"id": "acyclo",  "name": "Aciclovir", "category": "Antiviral", "route": "IV",
     "dose_mg_per_kg": 20, "dose_range": "10-20 mg/kg/dose", "frequency": "Every 8 h",
     "max_single_dose_mg": 800, "indication": "HSV encephalitis, neonatal HSV",
     "common_concentration_mg_per_ml": 25, "notes": "Ensure adequate hydration."},

    # ---- Steroid / anti-inflammatory ----
    {"id": "hydrocort","name": "Hydrocortisone", "category": "Steroid", "route": "IV",
     "dose_mg_per_kg": 4, "dose_range": "2-4 mg/kg", "frequency": "Every 6 h",
     "max_single_dose_mg": 100, "indication": "Anaphylaxis, adrenal crisis",
     "common_concentration_mg_per_ml": 50, "notes": ""},
    {"id": "dex",     "name": "Dexamethasone", "category": "Steroid", "route": "IV/PO",
     "dose_mg_per_kg": 0.15, "dose_range": "0.15-0.6 mg/kg", "frequency": "Every 6 h",
     "max_single_dose_mg": 10, "indication": "Croup, anti-inflammatory, cerebral oedema",
     "common_concentration_mg_per_ml": 4, "notes": "Croup dose usually 0.15 mg/kg PO/IV once."},
    {"id": "pred",    "name": "Prednisolone PO", "category": "Steroid", "route": "PO",
     "dose_mg_per_kg": 1, "dose_range": "1-2 mg/kg", "frequency": "Once daily",
     "max_single_dose_mg": 60, "indication": "Asthma exacerbation, autoimmune",
     "common_concentration_mg_per_ml": 3, "notes": ""},

    # ---- Seizures ----
    {"id": "diaz-iv", "name": "Diazepam IV", "category": "Anticonvulsant", "route": "IV",
     "dose_mg_per_kg": 0.3, "dose_range": "0.2-0.5 mg/kg", "frequency": "Once, may repeat once",
     "max_single_dose_mg": 10, "indication": "Status epilepticus",
     "common_concentration_mg_per_ml": 5, "notes": "PR route 0.5 mg/kg if no IV access."},
    {"id": "phen",    "name": "Phenytoin", "category": "Anticonvulsant", "route": "IV",
     "dose_mg_per_kg": 20, "dose_range": "20 mg/kg (loading)", "frequency": "Load over 20 min",
     "max_single_dose_mg": 1500, "indication": "Status epilepticus",
     "common_concentration_mg_per_ml": 50, "notes": "Cardiac monitoring. Only in NS (not dextrose)."},
    {"id": "levet",   "name": "Levetiracetam", "category": "Anticonvulsant", "route": "IV",
     "dose_mg_per_kg": 40, "dose_range": "20-60 mg/kg (loading)", "frequency": "Loading over 15 min",
     "max_single_dose_mg": 4500, "indication": "Status epilepticus",
     "common_concentration_mg_per_ml": 100, "notes": ""},

    # ---- Respiratory ----
    {"id": "salb-neb","name": "Salbutamol Nebulizer", "category": "Respiratory", "route": "Nebulized",
     "dose_mg_per_kg": 0.15, "dose_range": "0.15 mg/kg (min 2.5, max 5 mg)", "frequency": "Every 20 min ×3",
     "max_single_dose_mg": 5, "indication": "Acute asthma, bronchospasm",
     "common_concentration_mg_per_ml": 1, "notes": "5 mg/mL neb solution — dilute with NS to 4 mL."},
    {"id": "ipra-neb","name": "Ipratropium Nebulizer", "category": "Respiratory", "route": "Nebulized",
     "dose_mg_per_kg": 0.005, "dose_range": "250 mcg (<6y) or 500 mcg (≥6y)", "frequency": "Every 20 min ×3",
     "max_single_dose_mg": 0.5, "indication": "Acute severe asthma",
     "common_concentration_mg_per_ml": 0.25, "notes": "Combine with salbutamol for severe attacks."},

    # ---- GI / Antiemetic ----
    {"id": "ondan",   "name": "Ondansetron", "category": "Antiemetic", "route": "IV/PO",
     "dose_mg_per_kg": 0.15, "dose_range": "0.15 mg/kg", "frequency": "Every 8 h",
     "max_single_dose_mg": 8, "indication": "Nausea / vomiting",
     "common_concentration_mg_per_ml": 2, "notes": "QT prolongation risk with other agents."},
    {"id": "furos",   "name": "Furosemide", "category": "Diuretic", "route": "IV/PO",
     "dose_mg_per_kg": 1, "dose_range": "0.5-1 mg/kg", "frequency": "Every 6-12 h",
     "max_single_dose_mg": 40, "indication": "Fluid overload, pulmonary oedema",
     "common_concentration_mg_per_ml": 10, "notes": ""},
    {"id": "omez",    "name": "Omeprazole IV", "category": "GI", "route": "IV/PO",
     "dose_mg_per_kg": 1, "dose_range": "1 mg/kg", "frequency": "Once daily",
     "max_single_dose_mg": 40, "indication": "GERD, stress ulcer prophylaxis",
     "common_concentration_mg_per_ml": 4, "notes": ""},

    # ---- Fluids / electrolytes ----
    {"id": "fluidbolus","name": "Fluid Bolus (0.9% NaCl)", "category": "Fluids", "route": "IV/IO",
     "dose_ml_per_kg": 20, "dose_range": "10-20 mL/kg", "frequency": "May repeat",
     "max_single_dose_ml": 1000, "indication": "Shock, dehydration",
     "notes": "Reassess after each 20 mL/kg. Reduce to 10 mL/kg in DKA / cardiogenic."},
    {"id": "d10w",    "name": "Dextrose 10%", "category": "Fluids", "route": "IV/IO",
     "dose_ml_per_kg": 5, "dose_range": "5 mL/kg (=0.5 g/kg)", "frequency": "As needed",
     "max_single_dose_ml": 250, "indication": "Hypoglycaemia",
     "notes": "For infants use 5 mL/kg D10W; older children 2 mL/kg D25W."},
    {"id": "mannitol","name": "Mannitol 20%", "category": "Neuro", "route": "IV",
     "dose_mg_per_kg": 500, "dose_range": "0.25-1 g/kg", "frequency": "Every 4-6 h",
     "max_single_dose_mg": 100000, "indication": "Raised intracranial pressure",
     "common_concentration_mg_per_ml": 200, "notes": "Monitor osmolality and renal function."},
    {"id": "bicarb",  "name": "Sodium Bicarbonate 8.4%", "category": "Electrolyte", "route": "IV",
     "dose_ml_per_kg": 1, "dose_range": "1 mEq/kg (=1 mL/kg 8.4%)", "frequency": "As per pH",
     "max_single_dose_ml": 50, "indication": "Severe metabolic acidosis",
     "notes": "Dilute 1:1 with sterile water in neonates. Not routine in arrest."},
    {"id": "cagluc",  "name": "Calcium Gluconate 10%", "category": "Electrolyte", "route": "IV",
     "dose_mg_per_kg": 100, "dose_range": "60-100 mg/kg", "frequency": "As needed",
     "max_single_dose_mg": 3000, "indication": "Hypocalcaemia, hyperkalaemia, Ca-channel blocker OD",
     "common_concentration_mg_per_ml": 100, "notes": "Give slowly with cardiac monitoring."},
    {"id": "mgso4",   "name": "Magnesium Sulfate", "category": "Electrolyte", "route": "IV",
     "dose_mg_per_kg": 40, "dose_range": "25-50 mg/kg (over 20 min)", "frequency": "Single dose",
     "max_single_dose_mg": 2000, "indication": "Severe asthma, torsades",
     "common_concentration_mg_per_ml": 100, "notes": "Watch BP, reflexes."},
    {"id": "insulin", "name": "Insulin Infusion", "category": "Endocrine", "route": "IV",
     "dose_units_per_kg_per_hr": 0.1, "dose_range": "0.05-0.1 U/kg/hr", "frequency": "Continuous",
     "max_single_dose_units": 10, "indication": "DKA",
     "notes": "Do NOT bolus. Never stop unless glucose <4 or K falling."},
]


def broselow_zone_for(weight_kg: float):
    for z in BROSELOW_ZONES:
        if z["weight_kg_min"] <= weight_kg <= z["weight_kg_max"]:
            return z
    if weight_kg < BROSELOW_ZONES[0]["weight_kg_min"]:
        return BROSELOW_ZONES[0]
    return BROSELOW_ZONES[-1]
