"""
BSc Nursing procedures for years 1-4 + Abnormal delivery conditions.
Educational — always follow institutional protocol.
"""

# ==================== YEAR-WISE PROCEDURES ====================
NURSING_PROCEDURES = {
    "Year 1 — Fundamentals of Nursing": [
        {
            "id": "handwash",
            "name": "Handwashing (WHO 6-step technique)",
            "purpose": "Prevent healthcare-associated infection.",
            "articles": ["Soap / antimicrobial soap", "Running water", "Paper towel / hand dryer", "Optional: alcohol-based hand rub"],
            "steps": [
                "Remove jewellery, roll sleeves above elbows.",
                "Wet hands under running water.",
                "Apply soap (3-5 mL).",
                "Palm-to-palm rubbing.",
                "Right palm over left dorsum, interlaced fingers; then swap.",
                "Palm-to-palm with fingers interlaced.",
                "Backs of fingers against opposing palm.",
                "Rotational rubbing of left thumb in right palm; then swap.",
                "Rotational rubbing of clasped fingertips in the opposite palm.",
                "Rinse hands, dry with single-use towel, use towel to turn off tap.",
            ],
            "duration": "40-60 seconds (soap-and-water); 20-30 seconds (alcohol rub).",
            "tips": ["Never wear artificial nails.", "Alcohol rub preferred except when hands visibly soiled or after using loo."],
        },
        {
            "id": "bed-making",
            "name": "Bed making (closed / open / occupied)",
            "purpose": "Provide a clean, wrinkle-free, safe bed for the patient.",
            "articles": ["Bottom sheet", "Draw / mackintosh", "Top sheet", "Blanket", "Pillow with cover", "Bed cover / spread"],
            "steps": [
                "Perform hand hygiene, arrange linen in order of use.",
                "Loosen bedding on far side, then near side.",
                "Miter the corners (45°) to keep sheet tight.",
                "Place draw over mackintosh in the middle third.",
                "Tuck all layers on far side, then near side.",
                "For occupied bed: turn patient to far side, roll dirty linen to middle, place clean linen, turn patient over the roll, remove dirty linen, complete other side.",
            ],
            "tips": ["Never shake soiled linen — aerosolises microbes.", "Use bottom-to-top head-to-foot direction to avoid contamination."],
        },
        {
            "id": "vitals",
            "name": "Recording vital signs (T, P, R, BP, SpO₂)",
            "purpose": "Baseline & serial monitoring of physiological status.",
            "articles": ["Thermometer (digital / mercury / tympanic)", "Sphygmomanometer + stethoscope", "Pulse oximeter", "Wrist watch with seconds hand", "Vitals chart"],
            "steps": [
                "Explain procedure & wash hands.",
                "Temperature: axillary 5 min / oral 3 min / tympanic 1 sec.",
                "Radial pulse: count for 1 full minute — rate, rhythm, volume.",
                "Respirations: count 1 min while pretending to still take pulse.",
                "BP: correct cuff size (bladder ≈ 80% arm circumference), inflate 30 mmHg above disappearance of radial pulse, deflate 2-3 mmHg/sec, record Korotkoff I and V.",
                "SpO₂: warm finger, remove nail polish, wait 30 sec for stable reading.",
            ],
            "tips": ["Adult BP cuff too small = falsely HIGH reading.", "Cold / vasoconstricted finger = falsely LOW SpO₂."],
        },
        {
            "id": "im-injection",
            "name": "Intramuscular injection (Z-track / ventrogluteal)",
            "purpose": "Deliver medication into deep muscle for rapid absorption.",
            "articles": ["Prescribed drug + diluent", "Sterile syringe & needle 21-23 G", "Alcohol swab", "Sharps bin", "Gloves", "Kidney tray"],
            "steps": [
                "Verify 5-6 rights (patient, drug, dose, route, time, documentation).",
                "Choose site — ventrogluteal is safest in adults; vastus lateralis in infants.",
                "Position patient, expose site, clean skin in circular motion.",
                "Pull skin laterally (Z-track), insert needle at 90°, aspirate 5 sec.",
                "If no blood, inject slowly (1 mL/10 sec), release skin, withdraw needle.",
                "Do NOT massage site (irritating drugs). Dispose needle uncapped in sharps.",
            ],
            "tips": ["Never inject > 3 mL in deltoid or > 5 mL in gluteal.", "Aspirate is no longer recommended for vaccines but retained for other IM meds."],
        },
        {
            "id": "urinary-catheter",
            "name": "Urinary catheterization (female / male)",
            "purpose": "Continuous urinary drainage or accurate output measurement.",
            "articles": ["Catheter (Foley 12-14 F female / 14-16 F male)", "Sterile catheterization tray", "10-mL syringe of sterile water", "Water-soluble lubricant", "Urine bag", "Sterile gloves", "Antiseptic cleanser"],
            "steps": [
                "Explain procedure, ensure privacy, position (dorsal recumbent female / supine male).",
                "Hand hygiene, don sterile gloves, drape.",
                "Clean urethral meatus with antiseptic — front-to-back single stroke.",
                "Lubricate catheter tip (male 15-25 cm, female 5 cm).",
                "Insert catheter until urine flows, then advance 2-3 cm more.",
                "Inflate balloon with 10 mL sterile water. Attach to drainage bag secured below bladder level.",
            ],
            "tips": ["Aseptic technique is critical — CAUTI is preventable.", "Never force against resistance in males (stricture); consult urology."],
        },
        {
            "id": "ng-tube",
            "name": "Nasogastric tube insertion",
            "purpose": "Feeding, medication delivery, gastric decompression.",
            "articles": ["Ryle's / NG tube (14-16 F adult)", "Water-soluble jelly", "50-mL syringe", "Stethoscope", "Adhesive tape", "pH strip / X-ray order", "Cup of water with straw", "Kidney tray, tissue"],
            "steps": [
                "Measure NEX (nose → earlobe → xiphoid).",
                "Lubricate tip 6-10 cm.",
                "Advance tube along floor of nose; flex head when at oropharynx; ask alert patient to sip water and swallow while advancing.",
                "Check placement: aspirate stomach content, test pH (< 5.5). Chest X-ray is gold standard for confirmation.",
                "Secure to nose with tape; label date/time.",
            ],
            "tips": ["Auscultation of injected air is UNRELIABLE — do not rely on it alone.", "Stop and withdraw immediately if patient coughs, gags severely, or SpO₂ drops."],
        },
        {
            "id": "bed-bath",
            "name": "Bed bath",
            "purpose": "Personal hygiene for bed-bound patient.",
            "articles": ["Two basins (warm water)", "Washcloths ×2", "Towel ×2", "Soap", "Clean linen", "Lotion", "Gloves"],
            "steps": [
                "Ensure privacy, adjust room temperature.",
                "Wash face (eyes inner → outer canthus, one wipe per stroke).",
                "Neck, arms, chest, abdomen, legs (long strokes toward heart to promote venous return).",
                "Back — inspect for pressure areas, massage.",
                "Perineal area last with fresh water & cloth.",
            ],
            "tips": ["Change water when it becomes cool or dirty.", "Assess skin during bath — pressure ulcers, rashes, wounds."],
        },
    ],

    "Year 2 — Medical-Surgical & Pharmacology": [
        {
            "id": "iv-cannulation",
            "name": "Peripheral IV cannulation",
            "purpose": "Vascular access for fluids, drugs, blood products.",
            "articles": ["IV cannula 18-22 G", "Tourniquet", "Alcohol swab", "Sterile gauze", "Transparent dressing", "10-mL saline flush", "3-way stopcock / T-connector", "Gloves"],
            "steps": [
                "Choose non-dominant arm, distal veins first (dorsum of hand → forearm).",
                "Apply tourniquet 10 cm above site.",
                "Clean skin, allow to dry 30 sec.",
                "Anchor vein, insert cannula bevel-up at 15-30°.",
                "Flashback → advance cannula off stylet, release tourniquet, retract stylet, connect flush.",
                "Secure with transparent dressing, label date/time/size.",
            ],
            "tips": ["Avoid arm with AV fistula, mastectomy, paresis.", "PIVCs to be resited if signs of phlebitis (VIP score ≥ 2)."],
        },
        {
            "id": "blood-transfusion",
            "name": "Blood transfusion",
            "purpose": "Restore blood volume / RBC / clotting factors.",
            "articles": ["Cross-matched blood unit", "Blood transfusion set with 170-µm filter", "0.9% NS", "IV cannula ≥ 18 G", "Consent form", "Transfusion chart"],
            "steps": [
                "Verify consent, indication, and pre-transfusion vitals.",
                "Two-nurse check: patient ID, blood group, unit number, expiry, cross-match report.",
                "Prime line with NS only (never dextrose or Ringer's — haemolysis).",
                "Start slowly (2 mL/min × 15 min) — observe closely for reactions.",
                "If no reaction, adjust rate; complete within 4 hours.",
                "Monitor vitals: pre, 15 min, 30 min, hourly, and 1 h post.",
            ],
            "tips": ["Watch for TRALI (dyspnea + fever + hypotension), AHTR (chills, back pain, red urine).", "Stop transfusion, keep IV open with NS, notify physician for any reaction."],
        },
        {
            "id": "wound-dressing",
            "name": "Aseptic wound dressing",
            "purpose": "Promote healing, prevent infection.",
            "articles": ["Sterile dressing pack", "Sterile gloves", "Antiseptic (NS / chlorhexidine)", "Appropriate dressing (foam / hydrocolloid / gauze)", "Adhesive tape", "Waste bag"],
            "steps": [
                "Explain, hand hygiene, prepare sterile field.",
                "Remove old dressing with clean gloves; note discharge, odour.",
                "Assess wound size, depth, exudate (colour, amount).",
                "Change to sterile gloves.",
                "Clean wound from centre outward, or clean to dirty area — single stroke per swab.",
                "Apply topical if prescribed, cover with appropriate dressing.",
                "Document TIME framework (Tissue, Infection, Moisture, Edge).",
            ],
            "tips": ["Never use cotton wool directly on wounds — fibres stick.", "Photograph large / chronic wounds for serial comparison."],
        },
        {
            "id": "oxygen-therapy",
            "name": "Oxygen therapy (device selection)",
            "purpose": "Correct hypoxaemia while avoiding hyperoxia.",
            "articles": ["Oxygen source (wall / cylinder)", "Flowmeter + humidifier", "Nasal cannula / Simple mask / Venturi / Non-rebreather", "Pulse oximeter"],
            "steps": [
                "Assess SpO₂, RR, work of breathing.",
                "Choose device based on FiO₂ needed: NC 24-40% (1-6 L), Simple mask 40-60% (5-10 L), Venturi 24-60% (fixed), NRB 60-90% (10-15 L).",
                "Titrate to SpO₂ 94-98% (88-92% in COPD/CO₂ retainers).",
                "Monitor for hypercapnia in chronic lung disease.",
            ],
            "tips": ["Never use O₂ near open flame.", "Humidify at ≥ 4 L/min via nasal cannula to prevent drying."],
        },
        {
            "id": "suctioning",
            "name": "Endotracheal / Oropharyngeal suctioning",
            "purpose": "Clear airway secretions to prevent atelectasis and hypoxia.",
            "articles": ["Suction catheter (appropriate size ≤ ½ of ETT ID)", "Suction machine", "Sterile gloves", "Sterile NS", "Ambu bag with O₂ source", "Yankauer for oropharyngeal"],
            "steps": [
                "Pre-oxygenate with 100% O₂ for 30 sec (ventilated patient).",
                "Insert catheter WITHOUT suction until resistance felt, then withdraw 1 cm.",
                "Apply intermittent suction while rotating and withdrawing — MAX 10-15 sec.",
                "Allow patient to recover 30-60 sec between passes.",
                "Auscultate; document colour, consistency, amount.",
            ],
            "tips": ["Suction pressure: adult 100-150 mmHg, child 80-100 mmHg, infant 60-80 mmHg.", "Watch for hypoxia, bradycardia (vagal), bronchospasm."],
        },
        {
            "id": "ecg-recording",
            "name": "12-lead ECG recording",
            "purpose": "Record cardiac electrical activity for diagnosis.",
            "articles": ["ECG machine, leads and electrodes", "Alcohol swab / gel", "Razor (if hairy)"],
            "steps": [
                "Patient supine, expose chest, calm environment.",
                "Limb leads: RA, LA, RL (ground), LL.",
                "V1 — 4th ICS right sternal border; V2 — 4th ICS left sternal border; V4 — 5th ICS midclavicular line; V3 midway V2-V4; V5 — 5th ICS anterior axillary; V6 — 5th ICS mid-axillary line.",
                "Set paper speed 25 mm/sec, calibration 10 mm/mV.",
                "Ask patient to hold still + hold breath momentarily during recording.",
                "Label with patient name, date, time.",
            ],
            "tips": ["Right-sided leads (V3R-V6R) if inferior MI to rule out RV involvement.", "Posterior leads (V7-V9) if suspicion of posterior MI."],
        },
    ],

    "Year 3 — Community, Child & Mental Health": [
        {
            "id": "immunization",
            "name": "Immunization (following UIP schedule)",
            "purpose": "Prevent vaccine-preventable diseases.",
            "articles": ["Vaccine vials (cold chain 2-8°C)", "AD syringes", "Alcohol swab", "AEFI kit + adrenaline 1:1000", "Immunization card"],
            "steps": [
                "Verify vaccine, dose, route, expiry, VVM status.",
                "Explain to parent, obtain consent, assess contraindications.",
                "Site: BCG intradermal 0.05 mL (0.1 mL >1 y) left deltoid; OPV 2 drops oral; DPT/DT/TT IM anterolateral thigh; measles/MMR SC.",
                "Observe for 30 minutes for adverse events.",
                "Record on card + register (MCP).",
            ],
            "tips": ["BCG scar — reassure parent that scar 4-6 weeks after is expected.", "Never give live vaccines (BCG, OPV, Measles) to immunocompromised."],
        },
        {
            "id": "growth-monitoring",
            "name": "Growth monitoring (< 5 years)",
            "purpose": "Detect malnutrition and growth-faltering early.",
            "articles": ["Weighing scale (< 2 y salter / bassinet; > 2 y beam)", "Height / length rod (infantometer < 2 y)", "MUAC tape (6-59 m)", "Growth chart (WHO)"],
            "steps": [
                "Weigh with minimal clothing; record to nearest 100 g.",
                "Measure length (supine < 2 y) or height (standing ≥ 2 y).",
                "MUAC on left arm mid-point acromion-olecranon.",
                "Plot on WHO chart; classify z-scores: −2 SD moderate, −3 SD severe.",
            ],
            "tips": ["MUAC < 11.5 cm = severe acute malnutrition regardless of age (6-59 m).", "Growth-faltering: flat / falling curve is more important than a single reading."],
        },
        {
            "id": "orsl",
            "name": "ORS preparation & administration (home management of diarrhoea)",
            "purpose": "Prevent / treat dehydration in acute diarrhoea.",
            "articles": ["ORS packet (Low osmolarity WHO)", "Clean container", "1 L clean drinking water", "Cup + spoon", "Zinc supplement (10-14 days)"],
            "steps": [
                "Wash hands, dissolve entire packet in 1 L of clean water (never partial).",
                "Give: 50-100 mL after each loose stool (< 2 y); 100-200 mL (2-10 y); as much as wanted (> 10 y).",
                "Continue breastfeeding.",
                "Add zinc 20 mg/day (10 mg < 6 m) for 14 days.",
                "Teach danger signs: sunken eyes, no urine, lethargy → hospital.",
            ],
            "tips": ["Discard unused solution after 24 h.", "Never add sugar/salt — pre-measured formula only."],
        },
        {
            "id": "restraints",
            "name": "Application of physical restraints (mental-health / delirium)",
            "purpose": "Prevent self-harm or harm to others when least-restrictive measures fail.",
            "articles": ["4 or 5-point limb restraints", "Padded mittens", "Documentation form", "Physician's order"],
            "steps": [
                "Attempt least-restrictive alternatives first (de-escalation, family presence, medication).",
                "Obtain physician's written order (time-limited: 4 h adult, 2 h ≥ 9 y, 1 h < 9 y).",
                "Explain reason if patient can understand.",
                "Apply restraints with quick-release knots to the bed frame — never to side-rails.",
                "Check circulation, sensation, skin every 15 min for first hour then hourly.",
                "Release one limb at a time every 2 h for range-of-motion.",
                "Continuous 1-on-1 observation if 4-point restraint.",
            ],
            "tips": ["Restraint is ALWAYS temporary and MUST be re-evaluated hourly.", "Document rationale, less-restrictive measures tried, and time of release."],
        },
        {
            "id": "seizure-mgmt",
            "name": "Seizure management (safety-first approach)",
            "purpose": "Protect airway and prevent injury during and after a seizure.",
            "articles": ["Padded side-rails", "Oral airway (post-ictal only)", "Suction ready", "Oxygen source", "IV / rescue anticonvulsant (buccal midazolam / rectal diazepam)"],
            "steps": [
                "STAY WITH PATIENT — call for help; DO NOT restrain limbs.",
                "Move objects away; place a soft pillow under head; loosen tight clothing.",
                "Turn patient into left lateral recovery position once movements stop (or during if possible).",
                "Time the seizure — > 5 min = status epilepticus → rescue medication.",
                "Never put anything in the mouth during a seizure.",
                "Post-ictal: airway management, suction, O₂ if hypoxic.",
                "Document: time, duration, type of movement, LOC, incontinence, injuries.",
            ],
            "tips": ["Status epilepticus: buccal midazolam 10 mg / rectal diazepam 10 mg / IV lorazepam 4 mg — repeat once after 10 min if needed.", "Post-ictal drowsiness may last 30 min-2 h."],
        },
    ],

    "Year 4 — Midwifery / OBG & Management": [
        {
            "id": "antenatal-check",
            "name": "Antenatal check-up",
            "purpose": "Monitor maternal-fetal wellbeing throughout pregnancy.",
            "articles": ["BP apparatus", "Stethoscope + fetoscope / Doppler", "Weighing scale", "Measuring tape", "Urine dipstick", "Antenatal card", "Iron / folate / calcium supplements", "TT vaccine"],
            "steps": [
                "History — LMP, EDD (Naegele's: LMP + 9 months + 7 days), obstetric history (GPAL), medical / surgical / family history, current complaints.",
                "General examination — pallor, oedema, BP, weight, urine (protein / sugar).",
                "Abdominal — inspection (linea nigra, striae), fundal height (18-32 wk ≈ GA in weeks), Leopold's manoeuvres, fetal heart rate 110-160 bpm.",
                "Investigations — Hb, blood group + Rh, VDRL, HIV, HBsAg, blood sugar, urine RE, USG.",
                "Supplements — iron 60 mg + folic acid 500 μg daily from 2nd trimester; calcium 500 mg BD.",
                "Vaccination — TT/Td (2 doses in 1st pregnancy) or booster.",
                "Danger signs education — bleeding, headache, blurred vision, severe swelling, ↓ fetal movements.",
            ],
            "tips": ["Minimum 8 antenatal contacts per WHO 2016 guidelines.", "Fundal height should equal GA ±2 cm between 20-36 weeks."],
        },
        {
            "id": "partograph",
            "name": "Partograph (WHO-modified)",
            "purpose": "Graphic record of labour progress to detect prolonged / obstructed labour.",
            "articles": ["Partograph chart", "Fetoscope / Doppler", "BP apparatus", "Thermometer", "Sterile gloves for PV examination", "Timepiece"],
            "steps": [
                "Start when in active phase (cervical dilatation ≥ 4 cm, regular contractions).",
                "Record FHR every 30 min; contractions per 10 min; cervical dilatation every 4 h.",
                "Plot dilatation on chart — alert line + action line (4 h to the right).",
                "Record maternal vitals every 4 h, temperature every 4 h.",
                "Descent of head every 4 h (fifths palpable abdominally).",
                "If curve crosses ALERT LINE — reassess and consider intervention; if crosses ACTION LINE — active management.",
            ],
            "tips": ["Do not use during latent phase.", "Descent of head + cervical dilatation are the two key parameters."],
        },
        {
            "id": "normal-delivery",
            "name": "Conduct of normal delivery",
            "purpose": "Safe vaginal birth of a healthy baby.",
            "articles": ["Delivery set (sterile)", "Cord clamp × 2 + scissors", "Sterile gloves + gown", "Neonatal resuscitation trolley (warm, dry, stimulate, bag)", "Uterotonic (Oxytocin 10 IU IM ready)", "Kidney tray + placenta bowl"],
            "steps": [
                "1st stage — support, encourage, monitor per partograph.",
                "2nd stage: mother in lithotomy / semi-recumbent; encourage bearing down.",
                "Deliver head slowly between contractions; support perineum; feel for cord around neck.",
                "Deliver anterior shoulder with downward traction; then posterior shoulder upward; body slides out.",
                "Immediately dry & assess baby (breathing, tone).",
                "Delayed cord clamping 1-3 min if baby vigorous, then clamp × 2 and cut.",
                "3rd stage — Active management: Oxytocin 10 IU IM within 1 min of birth, controlled cord traction, uterine massage after placenta.",
                "Examine placenta for completeness (cotyledons, membranes).",
            ],
            "tips": ["AMTSL reduces PPH by 60%.", "Skin-to-skin contact within 1 hour + breastfeeding initiation."],
        },
        {
            "id": "episiotomy",
            "name": "Episiotomy & suturing",
            "purpose": "Selective enlargement of vaginal outlet when indicated (fetal distress, rigid perineum, instrumental delivery).",
            "articles": ["Episiotomy scissors", "Local anaesthetic (Lignocaine 1%)", "Needle holder + toothed forceps", "Chromic catgut 2-0 (or vicryl rapide)", "Sterile gauze"],
            "steps": [
                "Confirm indication + informed consent when possible.",
                "Infiltrate perineum with lignocaine along the intended cut.",
                "Cut mediolateral (starting from posterior fourchette, 45° from midline) at crowning.",
                "Suture in 3 layers post-delivery: vaginal mucosa (continuous), muscle (interrupted), skin (subcuticular).",
                "Ensure haemostasis, check haemostasis at hymenal ring, count swabs.",
            ],
            "tips": ["Restrictive rather than routine episiotomy (WHO).", "Post-op: perineal hygiene, analgesia, sitz bath."],
        },
    ],
}


# ==================== 30 ABNORMAL DELIVERY CONDITIONS ====================
ABNORMAL_DELIVERIES = [
    {"id": "shoulder-dystocia", "name": "Shoulder Dystocia", "definition": "Anterior shoulder impacted behind pubic symphysis after delivery of head.", "signs": ["Turtle sign — head retracts against perineum", "Delay in restitution", "Failure of shoulder to deliver with routine traction"], "management": ["Call for HELP (Help, Evaluate for episiotomy, Legs (McRoberts), Pressure suprapubic, Enter manoeuvres, Remove posterior arm, Roll onto all-fours)", "AVOID fundal pressure — causes further impaction", "Post-delivery: check for brachial plexus injury, clavicle fracture, PPH"]},
    {"id": "cord-prolapse", "name": "Umbilical Cord Prolapse", "definition": "Descent of umbilical cord below fetal presenting part after ROM.", "signs": ["Cord palpable on PV", "Sudden fetal bradycardia after ROM", "Cord visible outside introitus"], "management": ["Emergency LSCS — call for help", "Elevate presenting part manually off cord, keep hand there until delivery", "Knee-chest / Trendelenburg position", "Keep cord moist and warm; DO NOT push it back", "Fill bladder with 500 mL NS via Foley if delay expected"]},
    {"id": "pph-atonic", "name": "Postpartum Haemorrhage — Atonic Uterus", "definition": "Blood loss > 500 mL vaginal / > 1000 mL LSCS in 24 h due to failure of uterus to contract.", "signs": ["Soft, boggy uterus above the umbilicus", "Continuous vaginal bleeding", "Rising pulse, falling BP"], "management": ["4 T's mnemonic: Tone, Trauma, Tissue, Thrombin", "Bimanual uterine massage", "IV oxytocin 20 IU in 500 mL NS + methergine 0.2 mg IM (NOT if hypertensive) + carboprost 250 μg IM q15 min + misoprostol 800 μg PR", "Uterine balloon tamponade (Bakri)", "Blood products + surgical (B-Lynch, hysterectomy)"]},
    {"id": "pph-traumatic", "name": "Postpartum Haemorrhage — Traumatic", "definition": "PPH from perineal / vaginal / cervical laceration or uterine rupture.", "signs": ["Well-contracted uterus BUT active bleeding", "Visible tear on inspection"], "management": ["Systematic inspection under good light", "Repair tears in layers", "Uterine rupture → laparotomy"]},
    {"id": "retained-placenta", "name": "Retained Placenta", "definition": "Placenta not delivered within 30 minutes after birth.", "signs": ["Placenta not delivered", "Ongoing bleeding possible"], "management": ["Empty bladder", "Attempt controlled cord traction with uterine massage", "Manual removal in theatre under anaesthesia if failed", "Antibiotic prophylaxis"]},
    {"id": "inversion", "name": "Uterine Inversion", "definition": "Uterine fundus prolapses through cervix — obstetric emergency.", "signs": ["Severe pelvic pain immediately after delivery", "Absent uterus on abdominal palpation", "Vaginal mass / bleeding + neurogenic shock"], "management": ["Call for help + resuscitate — 2 large-bore IVs, fluids", "Immediate manual replacement (Johnson's manoeuvre) with placenta still in situ", "Terbutaline / MgSO4 for uterine relaxation", "Give uterotonics AFTER reduction"]},
    {"id": "rupture", "name": "Uterine Rupture", "definition": "Full-thickness disruption of uterine wall — usually along prior scar.", "signs": ["Severe abdominal pain (often referred to shoulder)", "Cessation of contractions", "Fetal parts easily palpable through abdomen", "Fetal distress or absent FH", "Shock"], "management": ["Immediate resuscitation + emergency laparotomy", "Blood transfusion", "Repair or hysterectomy per surgical judgement"]},
    {"id": "obstructed-labour", "name": "Obstructed Labour", "definition": "Failure of descent despite good uterine contractions.", "signs": ["Prolonged 2nd stage", "Bandl's ring", "Fetal distress, maternal dehydration and shock"], "management": ["Cease oxytocin", "IV fluids, cross-match, catheterise", "Emergency LSCS"]},
    {"id": "breech", "name": "Breech Presentation in Labour", "definition": "Buttocks / feet present rather than head.", "signs": ["Fetal head palpable in fundus", "FHR heard above umbilicus", "Feet / buttocks palpable on PV"], "management": ["ECV (external cephalic version) at 36-37 wks if singleton, no contraindication", "LSCS is preferred for term singleton breech (Term Breech Trial 2000)", "Assisted vaginal breech delivery only by experienced obstetrician"]},
    {"id": "transverse", "name": "Transverse / Oblique Lie", "definition": "Fetal long axis perpendicular to maternal long axis.", "signs": ["Elongated abdomen", "No presenting part felt on PV", "Shoulder / arm palpable"], "management": ["ECV at term if no contraindication", "LSCS if in labour or ECV fails", "Cord prolapse risk — avoid ARM before delivery"]},
    {"id": "face", "name": "Face Presentation", "definition": "Complete extension of fetal head — face is presenting.", "signs": ["Palpable mouth, nose, orbits on PV", "'Prominent occiput' on abdomen"], "management": ["Mento-anterior can deliver vaginally", "Mento-posterior → LSCS"]},
    {"id": "brow", "name": "Brow Presentation", "definition": "Partial extension — brow between anterior fontanelle and orbital ridges.", "signs": ["Palpable orbital ridges + anterior fontanelle on PV", "Largest fetal diameter (mento-vertical 13.5 cm) presents"], "management": ["Cannot deliver vaginally at term — LSCS", "Small preterm baby may convert to face or vertex"]},
    {"id": "compound", "name": "Compound Presentation", "definition": "A limb (hand / arm) prolapses alongside the head.", "signs": ["Hand felt beside head on PV"], "management": ["Observation if labour progressing well and limb small", "If arrest → attempt to push limb back or LSCS"]},
    {"id": "occipito-post", "name": "Persistent Occipito-Posterior (OP) Position", "definition": "Fetal occiput remains directed toward maternal sacrum.", "signs": ["Prolonged labour", "Severe back pain", "Anterior fontanelle palpable easily"], "management": ["Adequate analgesia, hydration, ambulation", "Manual rotation or forceps rotation by obstetrician", "LSCS if fails or fetal distress"]},
    {"id": "pre-eclampsia-severe", "name": "Severe Pre-eclampsia / Eclampsia", "definition": "BP ≥ 160/110 with proteinuria + end-organ damage (eclampsia = seizure).", "signs": ["Headache, blurred vision, epigastric pain", "Hyperreflexia, clonus", "Oliguria", "Tonic-clonic seizure (eclampsia)"], "management": ["Airway safety + left lateral", "MgSO4 loading 4 g IV over 5 min + 10 g IM, then 5 g IM q4h (or IV 1 g/hr)", "Labetalol / hydralazine / nifedipine to keep BP < 160/110", "Definitive treatment = delivery", "Monitor knee jerks, RR, UO — magnesium toxicity antidote = calcium gluconate"]},
    {"id": "abruption", "name": "Placental Abruption", "definition": "Premature separation of a normally-implanted placenta.", "signs": ["Painful vaginal bleeding (may be concealed)", "Tender, tense 'wooden' uterus", "Fetal distress or IUD", "Signs of shock"], "management": ["Resuscitate: 2 large-bore IVs, cross-match 4 units, catheterise", "Fetal alive + viable → LSCS", "Fetal dead / small → vaginal delivery if maternal condition permits", "Watch for DIC (send fibrinogen, D-dimer)"]},
    {"id": "previa", "name": "Placenta Praevia", "definition": "Placenta implanted in lower uterine segment covering / near internal os.", "signs": ["Painless, unprovoked, recurrent vaginal bleeding in 3rd trimester", "Malpresentation common"], "management": ["NEVER do a PV exam without USG confirmation", "Admit, 2 large-bore IVs, cross-match, monitor", "If minor bleed / preterm — conservative with steroids for lung maturity", "LSCS at 36-37 wks for major grades or if heavy bleeding"]},
    {"id": "accreta", "name": "Placenta Accreta Spectrum", "definition": "Abnormally adherent placenta (accreta / increta / percreta).", "signs": ["Retained placenta despite active management", "Severe PPH", "USG / MRI features"], "management": ["Anticipate: cross-match, ICU bed, senior obstetrician + urologist, interventional radiology", "Elective LSCS + hysterectomy is often the plan", "Do NOT force manual removal — massive haemorrhage"]},
    {"id": "vasa-previa", "name": "Vasa Praevia", "definition": "Fetal vessels traverse membranes across cervical os.", "signs": ["Painless vaginal bleeding at ARM / SROM with rapid fetal deterioration", "Vessels palpable on PV"], "management": ["Emergency LSCS", "Prenatal diagnosis by USG allows planned LSCS at 34-36 wks"]},
    {"id": "prom-preterm", "name": "Preterm Premature Rupture of Membranes (PPROM)", "definition": "ROM before 37 weeks and before labour.", "signs": ["Sudden gush of clear fluid", "Positive nitrazine / IGFBP-1 test", "Reduced liquor on USG"], "management": ["Admit + serial monitoring", "Antibiotics (erythromycin 250 mg PO qid × 10 days)", "Corticosteroids 24-34 wks (2 doses betamethasone 12 mg IM 24 h apart)", "MgSO4 for neuroprotection if < 32 wks", "Deliver at 34-37 wks or earlier if chorioamnionitis"]},
    {"id": "chorio", "name": "Chorioamnionitis", "definition": "Intra-amniotic infection.", "signs": ["Maternal fever + fetal tachycardia + uterine tenderness + foul-smelling liquor + maternal leucocytosis"], "management": ["Broad-spectrum IV antibiotics (Ampicillin + Gentamicin ± Metronidazole)", "Delivery — regardless of gestational age"]},
    {"id": "amniotic-embolism", "name": "Amniotic Fluid Embolism", "definition": "Rare catastrophic anaphylactoid response to amniotic fluid entering maternal circulation.", "signs": ["Sudden cardiovascular collapse", "Hypoxia", "DIC — bleeding from puncture sites"], "management": ["Immediate CPR + intubation + ionotropes", "Massive transfusion, correct DIC (FFP, cryo, platelets)", "Emergency LSCS if antepartum arrest"]},
    {"id": "preterm-labour", "name": "Preterm Labour", "definition": "Regular uterine contractions with cervical change before 37 weeks.", "signs": ["Cervical dilatation / effacement + contractions"], "management": ["Tocolytics (nifedipine 20 mg PO q30 min × 3 doses, then 20 mg q6h) — buy time for steroids", "Betamethasone 12 mg IM q24h × 2 doses (24-34 wks)", "MgSO4 for neuroprotection < 32 wks", "Antibiotics if GBS+ or PPROM"]},
    {"id": "iufd", "name": "Intrauterine Fetal Demise (IUFD)", "definition": "Fetal death > 20 weeks / ≥ 500 g.", "signs": ["Absent fetal movements", "Absent FH on Doppler / USG", "Fundal height less than dates"], "management": ["Empathy + counselling + emotional support", "Investigate cause (Kleihauer-Betke, TORCH, anticardiolipin, karyotype)", "Induction of labour — misoprostol / oxytocin", "Monitor for DIC if retained > 4 wks"]},
    {"id": "meconium", "name": "Meconium-Stained Liquor", "definition": "Fetal passage of meconium in utero — sign of fetal distress.", "signs": ["Greenish / brown-tinged amniotic fluid at ROM"], "management": ["Continuous CTG in labour", "Have paediatrician + resus equipment ready at delivery", "If baby vigorous — routine care", "If NOT vigorous — clear airway then PPV; avoid routine intrapartum suction"]},
    {"id": "gdm", "name": "Gestational Diabetes in Labour", "definition": "Glucose intolerance with onset in pregnancy.", "signs": ["Fasting > 5.1, 1-h > 10, 2-h > 8.5 mmol/L on OGTT"], "management": ["Frequent capillary BSL in labour (hourly)", "Target 4-7 mmol/L", "Insulin infusion if > 7 mmol/L consistently", "Anticipate macrosomia + shoulder dystocia, neonatal hypoglycaemia"]},
    {"id": "hellp", "name": "HELLP Syndrome", "definition": "Haemolysis, Elevated Liver enzymes, Low Platelets — severe pre-eclampsia variant.", "signs": ["RUQ pain + malaise + nausea", "Bruising, petechiae", "Abnormal LFTs, platelets < 100"], "management": ["Same as severe pre-eclampsia — MgSO4, BP control", "Delivery is definitive treatment", "Platelet transfusion if < 20 or < 50 and surgery planned", "Steroids may transiently improve platelets"]},
    {"id": "vbac-scar-dehis", "name": "Scar Dehiscence in VBAC", "definition": "Silent separation of previous LSCS scar during labour.", "signs": ["Sudden severe abdominal pain over the scar", "Loss of contractions", "Fetal bradycardia"], "management": ["Emergency LSCS", "May become uterine rupture if not intervened"]},
    {"id": "twin-locked", "name": "Locked Twins", "definition": "Rare complication of vaginal twin delivery — heads / bodies interlock.", "signs": ["Failure of descent after delivery of one part"], "management": ["Emergency LSCS", "Neonatal resus team ready — high mortality"]},
    {"id": "pre-labour-anaemia", "name": "Anaemia in Labour", "definition": "Hb < 10 g/dL affecting fetal oxygenation and increasing PPH risk.", "signs": ["Fatigue, pallor, tachycardia", "Poor tolerance of blood loss"], "management": ["Cross-match early, active management of 3rd stage", "IV iron sucrose antenatally if identified early", "Blood transfusion if Hb < 7 or symptomatic"]},
]
