"""Nurse Orbit backend seed data."""
from datetime import datetime, timedelta, timezone


SUBJECTS = [
    # Year 1
    {"id": "sub-fon", "year": "Year 1", "name": "Fundamentals of Nursing", "icon": "medical", "color": "#1E3A8A", "topics": 12, "lessons": 48},
    {"id": "sub-ana", "year": "Year 1", "name": "Anatomy", "icon": "body", "color": "#0D9488", "topics": 10, "lessons": 40},
    {"id": "sub-phy", "year": "Year 1", "name": "Physiology", "icon": "pulse", "color": "#3B82F6", "topics": 11, "lessons": 44},
    {"id": "sub-bio", "year": "Year 1", "name": "Biochemistry", "icon": "flask", "color": "#8B5CF6", "topics": 8, "lessons": 32},
    {"id": "sub-mic", "year": "Year 1", "name": "Microbiology", "icon": "bug", "color": "#0369A1", "topics": 9, "lessons": 36},
    # Year 2
    {"id": "sub-pha", "year": "Year 2", "name": "Pharmacology", "icon": "medkit", "color": "#0D9488", "topics": 14, "lessons": 56},
    {"id": "sub-pat", "year": "Year 2", "name": "Pathology", "icon": "warning", "color": "#EF4444", "topics": 10, "lessons": 40},
    {"id": "sub-msn", "year": "Year 2", "name": "Medical-Surgical Nursing", "icon": "bandage", "color": "#1E3A8A", "topics": 18, "lessons": 72},
    # Year 3
    {"id": "sub-chn", "year": "Year 3", "name": "Community Health Nursing", "icon": "people", "color": "#10B981", "topics": 9, "lessons": 36},
    {"id": "sub-cch", "year": "Year 3", "name": "Child Health Nursing", "icon": "happy", "color": "#F59E0B", "topics": 10, "lessons": 40},
    {"id": "sub-mhn", "year": "Year 3", "name": "Mental Health Nursing", "icon": "heart", "color": "#8B5CF6", "topics": 8, "lessons": 32},
    # Year 4
    {"id": "sub-obg", "year": "Year 4", "name": "Obstetric & Gynecological Nursing", "icon": "female", "color": "#EC4899", "topics": 12, "lessons": 48},
    {"id": "sub-res", "year": "Year 4", "name": "Nursing Research", "icon": "analytics", "color": "#3B82F6", "topics": 7, "lessons": 28},
    {"id": "sub-adm", "year": "Year 4", "name": "Nursing Administration", "icon": "briefcase", "color": "#0F172A", "topics": 8, "lessons": 32},
    # Specialties
    {"id": "sub-ccu", "year": "Clinical Specialties", "name": "Critical Care Nursing", "icon": "heart-circle", "color": "#EF4444", "topics": 10, "lessons": 40},
    {"id": "sub-emg", "year": "Clinical Specialties", "name": "Emergency Nursing", "icon": "flash", "color": "#F59E0B", "topics": 9, "lessons": 36},
]


LESSONS = {
    "sub-pha": [
        {"id": "les-pha-1", "title": "Introduction to Pharmacology", "duration": "15 min", "objectives": ["Define pharmacology and its branches", "Explain drug nomenclature", "Describe drug classification"], "key_concepts": "Pharmacology is the study of drugs and their interactions with living organisms. It includes pharmacokinetics (what the body does to the drug) and pharmacodynamics (what the drug does to the body).", "clinical_notes": "Always verify the 'Six Rights' of medication administration: right patient, right drug, right dose, right route, right time, right documentation.", "references": "Lehne's Pharmacology for Nursing Care, 11th ed."},
        {"id": "les-pha-2", "title": "Cardiovascular Drugs - Antihypertensives", "duration": "20 min", "objectives": ["Classify antihypertensive drugs", "Describe mechanism of ACE inhibitors", "Identify nursing considerations for beta-blockers"], "key_concepts": "Major classes include ACE inhibitors (-pril), ARBs (-sartan), beta-blockers (-olol), calcium channel blockers, and diuretics. ACE inhibitors block the conversion of angiotensin I to angiotensin II, reducing vasoconstriction.", "clinical_notes": "Monitor blood pressure before administration. Common side effect of ACE inhibitors is a dry, persistent cough. Beta-blockers should not be abruptly discontinued.", "references": "AHA/ACC Guidelines for the Management of Hypertension"},
        {"id": "les-pha-3", "title": "Anticoagulants and Antiplatelets", "duration": "18 min", "objectives": ["Differentiate anticoagulants from antiplatelets", "State reversal agents", "Identify bleeding precautions"], "key_concepts": "Heparin works by activating antithrombin III. Warfarin inhibits vitamin K-dependent clotting factors. DOACs like apixaban directly inhibit factor Xa.", "clinical_notes": "Reversal: Protamine sulfate for heparin, Vitamin K for warfarin. Monitor aPTT for heparin, INR for warfarin. Assess for bleeding signs.", "references": "ISTH Guidelines on Anticoagulation"},
    ],
    "sub-msn": [
        {"id": "les-msn-1", "title": "Assessment of the Cardiovascular System", "duration": "22 min", "objectives": ["Perform a focused cardiac assessment", "Interpret heart sounds", "Recognize signs of decreased cardiac output"], "key_concepts": "Systematic assessment includes inspection, palpation, percussion, and auscultation. Normal heart sounds are S1 (lub) and S2 (dub). S3 may indicate heart failure; S4 may indicate stiff ventricle.", "clinical_notes": "Use the diaphragm for high-pitched sounds (S1, S2) and the bell for low-pitched sounds (S3, S4). Check for jugular venous distention and peripheral edema.", "references": "Brunner & Suddarth's Textbook of Medical-Surgical Nursing"},
    ],
}


QUESTIONS = [
    {
        "id": "q1",
        "subject_id": "sub-pha",
        "topic": "Cardiovascular Drugs",
        "difficulty": "medium",
        "question": "A patient taking an ACE inhibitor complains of a persistent dry cough. Which is the nurse's best action?",
        "options": [
            "Advise the patient to stop the medication immediately",
            "Notify the healthcare provider as this may require a medication change",
            "Reassure the patient this is expected and will resolve",
            "Administer a cough suppressant",
        ],
        "correct_index": 1,
        "explanation": "A persistent dry cough is a well-known side effect of ACE inhibitors due to bradykinin accumulation. The nurse should notify the provider, who may switch the patient to an ARB.",
        "rationale": "ACE inhibitors block the breakdown of bradykinin, leading to cough in ~10% of patients. Discontinuation must be provider-directed.",
        "reference": "Lehne's Pharmacology, Ch. 47",
        "option_explanations": [
            "A: Stopping the medication abruptly could be dangerous; this decision must be made by the provider.",
            "B: Correct — a persistent cough is a known ACE inhibitor side effect requiring provider assessment for a medication change.",
            "C: This cough does not resolve on its own; it is a pharmacological effect of the drug class.",
            "D: A cough suppressant treats the symptom, not the cause, and does not address the need for a medication change.",
        ],
        "remember_this": "ACE inhibitors → bradykinin build-up → dry cough → document and notify provider for ARB switch.",
    },
    {
        "id": "q2",
        "subject_id": "sub-pha",
        "topic": "Anticoagulants",
        "difficulty": "hard",
        "question": "Which laboratory value should be monitored for a patient receiving IV heparin?",
        "options": ["INR", "aPTT", "Platelet count only", "PT"],
        "correct_index": 1,
        "explanation": "aPTT (activated partial thromboplastin time) is the standard lab used to monitor heparin therapy. Target range is typically 1.5-2.5 times the control value.",
        "rationale": "Heparin potentiates antithrombin III, affecting the intrinsic pathway measured by aPTT. INR/PT monitor warfarin.",
        "reference": "ISTH Guidelines",
        "option_explanations": [
            "A: INR (International Normalized Ratio) monitors warfarin therapy, not unfractionated heparin.",
            "B: Correct — aPTT assesses the intrinsic pathway and is the standard metric used to titrate IV heparin therapy.",
            "C: While platelets must be monitored for heparin-induced thrombocytopenia (HIT), aPTT is required for therapeutic dosing.",
            "D: PT (prothrombin time) evaluates the extrinsic pathway and is used for warfarin rather than IV heparin.",
        ],
        "remember_this": "Heparin titrates with aPTT (intrinsic pathway); Warfarin titrates with PT/INR (extrinsic pathway).",
    },
    {
        "id": "q3",
        "subject_id": "sub-msn",
        "topic": "Cardiovascular Assessment",
        "difficulty": "easy",
        "question": "Which heart sound is most commonly associated with heart failure in adults?",
        "options": ["S1", "S2", "S3", "Physiologic split S2"],
        "correct_index": 2,
        "explanation": "An S3 heart sound in adults over 40 is often a sign of ventricular dysfunction and heart failure. It results from rapid ventricular filling into a non-compliant ventricle.",
        "rationale": "S3 is best heard at the apex with the bell of the stethoscope in the left lateral position.",
        "reference": "Brunner & Suddarth's",
        "option_explanations": [
            "A: S1 is the normal 'lub' sound generated by the closure of the mitral and tricuspid valves.",
            "B: S2 is the normal 'dub' sound created by the closure of the aortic and pulmonic valves.",
            "C: Correct — S3 (ventricular gallop) indicates sudden deceleration of blood flow into a dilated, non-compliant ventricle in adult heart failure.",
            "D: Physiologic split S2 is a benign finding heard during inspiration due to delayed closure of the pulmonic valve.",
        ],
        "remember_this": "Adult S3 = 'Kentucky' ventricular gallop → classic sign of volume overload and congestive heart failure.",
    },
    {
        "id": "q4",
        "subject_id": "sub-fon",
        "topic": "Medication Administration",
        "difficulty": "easy",
        "question": "Which of the following is NOT one of the traditional 'Rights' of medication administration?",
        "options": ["Right dose", "Right route", "Right cost", "Right time"],
        "correct_index": 2,
        "explanation": "The traditional six rights are: right patient, right drug, right dose, right route, right time, and right documentation. Cost is not one of them.",
        "rationale": "Some texts add right reason, right response, and right to refuse, but cost is a system consideration, not a right.",
        "reference": "Fundamentals of Nursing, Potter & Perry",
        "option_explanations": [
            "A: Right dose is an indispensable medication right that prevents subtherapeutic outcomes or medication overdose.",
            "B: Right route ensures safe delivery through the prescribed anatomical pathway (e.g., PO, IV, SC).",
            "C: Correct — right cost is an administrative or insurance consideration, not one of the patient safety rights of administration.",
            "D: Right time guarantees therapeutic drug concentration levels and prevents cumulative toxicity.",
        ],
        "remember_this": "Rights of Medication Administration focus strictly on clinical safety: Patient, Drug, Dose, Route, Time, and Documentation.",
    },
    {
        "id": "q5",
        "subject_id": "sub-fon",
        "topic": "Infection Control",
        "difficulty": "medium",
        "question": "The most effective single measure to prevent healthcare-associated infections is:",
        "options": ["Wearing gloves at all times", "Hand hygiene", "Isolation precautions", "Sterile technique"],
        "correct_index": 1,
        "explanation": "Hand hygiene, performed correctly and consistently, is the single most effective intervention to prevent HAIs, per WHO and CDC.",
        "rationale": "The WHO 'My Five Moments for Hand Hygiene' guides clinical practice.",
        "reference": "WHO Guidelines on Hand Hygiene in Health Care",
        "option_explanations": [
            "A: Gloves act as barrier protection but are not a substitute for hand hygiene and can spread pathogens if not changed.",
            "B: Correct — hand hygiene (washing or alcohol rub) is recognized by CDC/WHO as the single most effective intervention against HAIs.",
            "C: Isolation precautions manage specific transmissible pathogens but do not prevent broader cross-contamination.",
            "D: Sterile technique is necessary during invasive procedures but does not replace standard hand cleanliness between patients.",
        ],
        "remember_this": "Consistent hand hygiene is the single most effective barrier against healthcare-associated infections (HAIs).",
    },
    {
        "id": "q6",
        "subject_id": "sub-mhn",
        "topic": "Therapeutic Communication",
        "difficulty": "medium",
        "question": "A patient states, 'I feel like nobody understands me.' Which is the most therapeutic response?",
        "options": ["'Everyone feels that way sometimes.'", "'Tell me more about that feeling.'", "'You should talk to your family.'", "'Why do you feel that way?'"],
        "correct_index": 1,
        "explanation": "'Tell me more' is an open-ended, exploratory response that invites the patient to share, demonstrating active listening.",
        "rationale": "Why questions can feel confrontational. Reassurance and advice-giving are non-therapeutic.",
        "reference": "Videbeck, Psychiatric-Mental Health Nursing",
        "option_explanations": [
            "A: Minimizes and dismisses the patient's unique experience, shutting down meaningful expression.",
            "B: Correct — 'Tell me more' is an open-ended, exploratory prompt that communicates empathy and invites the patient to elaborate.",
            "C: Giving unsolicited advice deflects from the immediate nurse-patient therapeutic relationship.",
            "D: Asking 'why' implies interrogation or judgment and tends to make patients defensive.",
        ],
        "remember_this": "Therapeutic communication uses open-ended exploration ('Tell me more') and avoids non-therapeutic 'Why' questions.",
    },
    {
        "id": "q7",
        "subject_id": "sub-cch",
        "topic": "Pediatric Vitals",
        "difficulty": "medium",
        "question": "The normal resting heart rate range for a 2-year-old toddler is:",
        "options": ["60-100 bpm", "80-120 bpm", "90-140 bpm", "120-160 bpm"],
        "correct_index": 2,
        "explanation": "Toddlers (1-3 years) have a normal HR of approximately 90-140 bpm. Rates decrease with age.",
        "rationale": "120-160 is infant range; 60-100 is adult.",
        "reference": "Wong's Nursing Care of Infants and Children",
        "option_explanations": [
            "A: 60-100 bpm is the resting heart rate range for normal adults and adolescents, which is bradycardic for a toddler.",
            "B: 80-120 bpm is typical for preschoolers (3-5 years) or school-age children.",
            "C: Correct — 90-140 bpm is the normal resting pulse rate range for a toddler aged 1 to 3 years.",
            "D: 120-160 bpm is the normal resting heart rate range for infants under 1 year of age.",
        ],
        "remember_this": "Resting HR decreases with development: Infant (120-160) → Toddler (90-140) → Preschool (80-120) → Adult (60-100).",
    },
    {
        "id": "q8",
        "subject_id": "sub-obg",
        "topic": "Antenatal Care",
        "difficulty": "hard",
        "question": "Naegele's rule for calculating the estimated date of delivery is:",
        "options": ["Add 9 months and 7 days to LMP", "Subtract 3 months and add 7 days to LMP", "Add 280 days from conception", "Subtract 3 months from LMP"],
        "correct_index": 1,
        "explanation": "Naegele's rule: Subtract 3 months from the first day of the last menstrual period (LMP) and add 7 days (and 1 year).",
        "rationale": "This assumes a regular 28-day cycle.",
        "reference": "Lowdermilk, Maternity & Women's Health Care",
        "option_explanations": [
            "A: Adding 9 months can cause calendar discrepancy errors; standard Naegele's rule subtracts 3 months, adds 7 days, and adds 1 year.",
            "B: Correct — Naegele's rule calculates the estimated delivery date by subtracting 3 months and adding 7 days to the first day of the LMP.",
            "C: 280 days is measured from the first day of the LMP, not from conception (which is approximately 266 days).",
            "D: Subtracting 3 months alone omits the 7 days and year adjustment needed to calculate the EDD.",
        ],
        "remember_this": "Naegele's Rule: LMP minus 3 months plus 7 days (+ 1 year) = Estimated Date of Delivery (EDD).",
    },
    {
        "id": "q9",
        "subject_id": "sub-ccu",
        "topic": "Cardiac Arrhythmias",
        "difficulty": "hard",
        "question": "Which rhythm is 'shockable' during a cardiac arrest according to ACLS guidelines?",
        "options": ["Asystole", "Pulseless Electrical Activity (PEA)", "Ventricular Fibrillation", "Sinus Bradycardia"],
        "correct_index": 2,
        "explanation": "VF and pulseless VT are the shockable rhythms in ACLS. Asystole and PEA are managed with CPR and epinephrine.",
        "rationale": "Defibrillation is only effective for VF/pVT.",
        "reference": "AHA ACLS Guidelines 2020",
        "option_explanations": [
            "A: Asystole has no electrical activity to depolarize; treat with high-quality CPR and epinephrine, not defibrillation.",
            "B: PEA presents electrical rhythm without mechanical contraction; treat with CPR and identifying the 5 H's and 5 T's, never shock.",
            "C: Correct — Ventricular Fibrillation (and pulseless VT) are disorganized rhythms that require immediate unsynchronized defibrillation.",
            "D: Sinus Bradycardia is an organized rhythm with a pulse; defibrillation during cardiac arrest algorithms does not apply.",
        ],
        "remember_this": "ACLS Cardiac Arrest: Only VF and Pulseless VT are shockable. Asystole and PEA require CPR and Epinephrine.",
    },
    {
        "id": "q10",
        "subject_id": "sub-emg",
        "topic": "Triage",
        "difficulty": "medium",
        "question": "Using the Emergency Severity Index (ESI), a patient with chest pain and stable vitals is typically triaged as:",
        "options": ["ESI Level 1", "ESI Level 2", "ESI Level 3", "ESI Level 5"],
        "correct_index": 1,
        "explanation": "ESI Level 2 (emergent) is assigned to patients in high-risk situations (like chest pain) even when currently stable, requiring rapid assessment.",
        "rationale": "Level 1 is immediately life-threatening. Level 5 is non-urgent.",
        "reference": "ENA ESI Handbook",
        "option_explanations": [
            "A: ESI Level 1 is reserved for patients in immediate cardiac or respiratory arrest requiring immediate life-saving intervention.",
            "B: Correct — ESI Level 2 denotes high-risk clinical scenarios like potential acute coronary syndrome even when vitals appear stable.",
            "C: ESI Level 3 is for stable patients needing multiple resources without high-risk presentation markers.",
            "D: ESI Level 5 is non-urgent and requires zero anticipated emergency department resources.",
        ],
        "remember_this": "ESI Level 2 = High-risk situation (chest pain, acute stroke, suicidal ideation) even if vitals are currently stable.",
    },
]


EXAMS = [
    {"id": "exam-doh", "country": "UAE", "flag": "🇦🇪", "name": "DOH Abu Dhabi", "full_name": "Department of Health – Abu Dhabi", "overview": "The DOH exam is required to practice as a licensed nurse in the Emirate of Abu Dhabi. Administered via Pearson VUE.", "eligibility": "Registered Nurse with a minimum of 2 years post-registration clinical experience.", "education": "Bachelor's degree in Nursing (BSc) or equivalent 3-year Diploma (GNM) with additional experience.", "documents": ["Passport copy", "Educational certificates (attested)", "Registration/license", "Experience certificates", "Good Standing Certificate", "DataFlow report"], "process": "1. Create account on Sheryan portal. 2. Submit documents for DataFlow verification. 3. Book exam via Pearson VUE. 4. Pass exam. 5. Apply for license.", "renewal": "Every 1-2 years with CME hours.", "official": "https://www.doh.gov.ae"},
    {"id": "exam-dha", "country": "UAE", "flag": "🇦🇪", "name": "DHA Dubai", "full_name": "Dubai Health Authority", "overview": "DHA licensing exam for nurses practicing in Dubai. Administered via Prometric.", "eligibility": "Registered Nurse with a minimum of 2 years clinical experience.", "education": "BSc Nursing (4 years) or equivalent qualification recognized by DHA.", "documents": ["Passport", "Educational certificates", "License", "Experience letters", "PSV via DataFlow"], "process": "1. DHA Sheryan account. 2. DataFlow PSV. 3. Prometric exam booking. 4. Eligibility letter. 5. License issuance.", "renewal": "Every 2 years with 20 CME hours.", "official": "https://www.dha.gov.ae"},
    {"id": "exam-mohap", "country": "UAE", "flag": "🇦🇪", "name": "MOHAP", "full_name": "Ministry of Health & Prevention", "overview": "MOHAP license for practice in northern emirates (Sharjah, Ajman, Ras Al Khaimah, Fujairah, Umm Al Quwain).", "eligibility": "RN with clinical experience.", "education": "Diploma/Bachelor's in Nursing.", "documents": ["Standard credentials packet"], "process": "MOHAP portal → PSV → Prometric → License.", "renewal": "Every 2 years.", "official": "https://mohap.gov.ae"},
    {"id": "exam-scfhs", "country": "Saudi Arabia", "flag": "🇸🇦", "name": "SCFHS Prometric", "full_name": "Saudi Commission for Health Specialties", "overview": "SCFHS licensing exam for all nurses working in Saudi Arabia.", "eligibility": "Registered Nurse.", "education": "Diploma or Bachelor's in Nursing.", "documents": ["Standard credentials"], "process": "Mumaris+ registration → Prometric exam → Classification → License.", "renewal": "Every 2 years with CPD.", "official": "https://scfhs.org.sa"},
    {"id": "exam-qchp", "country": "Qatar", "flag": "🇶🇦", "name": "QCHP", "full_name": "Qatar Council for Healthcare Practitioners", "overview": "QCHP license for practicing in Qatar hospitals.", "eligibility": "RN with 2+ years experience.", "education": "BSc Nursing preferred.", "documents": ["Passport, license, degree, experience"], "process": "QCHP portal → Assessment → Prometric → License.", "renewal": "Every 2 years.", "official": "https://qchp.org.qa"},
    {"id": "exam-omsb", "country": "Oman", "flag": "🇴🇲", "name": "OMSB", "full_name": "Oman Medical Specialty Board", "overview": "Licensing pathway for nurses in the Sultanate of Oman.", "eligibility": "RN with valid registration.", "education": "Diploma or Bachelor's.", "documents": ["Standard packet"], "process": "OMSB portal → PSV → Exam → License.", "renewal": "Every 2 years.", "official": "https://omsb.gov.om"},
    {"id": "exam-nmc", "country": "UK", "flag": "🇬🇧", "name": "NMC (UK)", "full_name": "Nursing and Midwifery Council", "overview": "Registration with the NMC requires the CBT (Computer-Based Test) and OSCE (Objective Structured Clinical Examination).", "eligibility": "Qualified nurse with recognized education.", "education": "Minimum 4600 hours combined theory and practice.", "documents": ["English test (IELTS/OET)", "ID", "Qualifications", "Registration abroad", "Good Health & Character"], "process": "NMC application → CBT → UK visa → OSCE → Registration.", "renewal": "Every 3 years with revalidation.", "official": "https://www.nmc.org.uk"},
    {"id": "exam-nclex-us", "country": "USA", "flag": "🇺🇸", "name": "NCLEX-RN (USA)", "full_name": "National Council Licensure Examination", "overview": "NCLEX-RN is required for RN licensure in all US states.", "eligibility": "Graduate of an approved nursing program; state Board approval.", "education": "ADN or BSN in Nursing.", "documents": ["Transcripts", "CGFNS/Credential eval", "State BON application"], "process": "Apply to State BON → Credential evaluation (CGFNS) → ATT → Pearson VUE → License.", "renewal": "Varies by state (usually 2 years).", "official": "https://www.ncsbn.org"},
    {"id": "exam-nclex-ca", "country": "Canada", "flag": "🇨🇦", "name": "NCLEX-RN (Canada)", "full_name": "NCLEX-RN via NNAS", "overview": "IENs apply through NNAS then to the provincial regulator, then write NCLEX-RN.", "eligibility": "IEN with NNAS advisory report.", "education": "Nursing qualification comparable to Canadian entry-to-practice.", "documents": ["NNAS documents", "IELTS/CELBAN", "Provincial regulator packet"], "process": "NNAS → Provincial application → NCLEX-RN → License.", "renewal": "Annual with CE.", "official": "https://www.nnas.ca"},
    {"id": "exam-ahpra", "country": "Australia", "flag": "🇦🇺", "name": "AHPRA / OBA", "full_name": "Australian Health Practitioner Regulation Agency", "overview": "IENs may need to complete the Outcomes-Based Assessment (OBA) to register.", "eligibility": "IEN with comparable qualification.", "education": "Bachelor's in Nursing.", "documents": ["English test (IELTS/OET/PTE)", "AHPRA portfolio"], "process": "AHPRA online portfolio → OBA (MCQ + OSCE) → Registration.", "renewal": "Annual with CPD.", "official": "https://www.ahpra.gov.au"},
]


PATHWAYS = [
    {"id": "pth-de", "country": "Germany", "flag": "🇩🇪", "demand": "Very High", "language": "German B1/B2", "steps": [
        {"n": 1, "title": "Check eligibility", "desc": "Confirm your nursing qualification meets German recognition standards."},
        {"n": 2, "title": "Prepare documents", "desc": "Get transcripts, license, and experience letters translated and apostilled."},
        {"n": 3, "title": "German A1", "desc": "Basic conversational German."},
        {"n": 4, "title": "German A2", "desc": "Elementary German usage."},
        {"n": 5, "title": "German B1", "desc": "Independent use of German – required minimum for recognition in most states."},
        {"n": 6, "title": "German B2", "desc": "Preferred for clinical practice and Kenntnisprüfung."},
        {"n": 7, "title": "Recognition (Anerkennung)", "desc": "Submit to relevant state authority; may include adaptation course or exam (Kenntnisprüfung)."},
        {"n": 8, "title": "Find an employer", "desc": "Secure a signed contract from a German hospital."},
        {"n": 9, "title": "Visa (§16d)", "desc": "Apply for Recognition/Employment visa at German consulate."},
        {"n": 10, "title": "Arrival & integration", "desc": "Register (Anmeldung), open bank, sign work contract, start Anerkennung program."},
    ]},
    {"id": "pth-uae", "country": "UAE", "flag": "🇦🇪", "demand": "High", "language": "English", "steps": [
        {"n": 1, "title": "Verify qualifications", "desc": "Ensure BSc/Diploma is accredited."},
        {"n": 2, "title": "Prepare documents", "desc": "Attestation from home country and UAE embassy."},
        {"n": 3, "title": "DataFlow PSV", "desc": "Primary Source Verification of credentials."},
        {"n": 4, "title": "Choose emirate", "desc": "DOH, DHA, or MOHAP."},
        {"n": 5, "title": "Prometric / DOH exam", "desc": "Pass licensing exam."},
        {"n": 6, "title": "Get eligibility letter", "desc": "Receive letter allowing job applications."},
        {"n": 7, "title": "Employer offer", "desc": "Secure a job offer."},
        {"n": 8, "title": "Employment visa", "desc": "Employer processes visa."},
        {"n": 9, "title": "Arrive & activate license", "desc": "Emirates ID, license issuance."},
    ]},
    {"id": "pth-uk", "country": "UK", "flag": "🇬🇧", "demand": "High", "language": "English (IELTS/OET)", "steps": [
        {"n": 1, "title": "English test", "desc": "IELTS 7.0 or OET B."},
        {"n": 2, "title": "NMC application", "desc": "Apply and submit qualifications for evaluation."},
        {"n": 3, "title": "CBT", "desc": "Pass Computer-Based Test."},
        {"n": 4, "title": "Employer sponsor", "desc": "Get Certificate of Sponsorship."},
        {"n": 5, "title": "Skilled Worker visa", "desc": "Health & Care Worker visa."},
        {"n": 6, "title": "OSCE (in UK)", "desc": "Objective Structured Clinical Exam."},
        {"n": 7, "title": "NMC registration", "desc": "Full PIN, start practice."},
    ]},
    {"id": "pth-us", "country": "USA", "flag": "🇺🇸", "demand": "High", "language": "English", "steps": [
        {"n": 1, "title": "State Board application", "desc": "Choose state; apply to Board of Nursing."},
        {"n": 2, "title": "CGFNS / Credential eval", "desc": "Get credentials evaluated."},
        {"n": 3, "title": "NCLEX-RN", "desc": "Pass the NCLEX examination."},
        {"n": 4, "title": "English test", "desc": "TOEFL/IELTS if required by state."},
        {"n": 5, "title": "Employer sponsor", "desc": "Secure US employer offer."},
        {"n": 6, "title": "Immigrant visa", "desc": "EB-3 or H-1C petition."},
        {"n": 7, "title": "License activation", "desc": "State license issued."},
    ]},
    {"id": "pth-ca", "country": "Canada", "flag": "🇨🇦", "demand": "High", "language": "English/French", "steps": [
        {"n": 1, "title": "NNAS application", "desc": "National Nursing Assessment Service."},
        {"n": 2, "title": "Language test", "desc": "IELTS/CELBAN/TEF."},
        {"n": 3, "title": "Provincial regulator", "desc": "Apply to CNO, BCCNM, CRNBC etc."},
        {"n": 4, "title": "NCLEX-RN", "desc": "Pass the exam."},
        {"n": 5, "title": "Express Entry / PR", "desc": "Immigration pathway."},
        {"n": 6, "title": "Arrival & registration", "desc": "Complete jurisdictional requirements."},
    ]},
    {"id": "pth-au", "country": "Australia", "flag": "🇦🇺", "demand": "High", "language": "English", "steps": [
        {"n": 1, "title": "AHPRA portfolio", "desc": "Submit online self-check."},
        {"n": 2, "title": "English test", "desc": "IELTS 7.0 / OET B / PTE."},
        {"n": 3, "title": "OBA – MCQ", "desc": "Outcomes-based assessment (multi-choice)."},
        {"n": 4, "title": "OBA – OSCE", "desc": "Clinical assessment in Australia."},
        {"n": 5, "title": "AHPRA registration", "desc": "Get NMBA registration."},
        {"n": 6, "title": "Visa & employment", "desc": "Skilled visa (subclass 189/190/482)."},
    ]},
    {"id": "pth-sa", "country": "Saudi Arabia", "flag": "🇸🇦", "demand": "Very High", "language": "English", "steps": [
        {"n": 1, "title": "Documents", "desc": "Attestation via home MoFA + Saudi embassy."},
        {"n": 2, "title": "DataFlow PSV", "desc": "Primary Source Verification."},
        {"n": 3, "title": "SCFHS Mumaris+", "desc": "Register on Mumaris+ platform."},
        {"n": 4, "title": "Prometric exam", "desc": "Pass SCFHS Prometric."},
        {"n": 5, "title": "Classification", "desc": "Get classified as staff nurse/specialist."},
        {"n": 6, "title": "Employer & visa", "desc": "Work permit and visa."},
    ]},
]


NEWS = [
    {"id": "news-1", "category": "UAE", "headline": "DOH Abu Dhabi announces updated nursing license renewal fees for 2026", "image": "https://images.unsplash.com/photo-1587351021355-a479a299d2f9?w=800", "source": "DOH Announcements", "date": "2026-04-28", "summary": "The Department of Health Abu Dhabi has revised the renewal fee schedule for professional nursing licenses effective April 2026. The new structure introduces tiered rates based on specialty."},
    {"id": "news-2", "category": "Germany", "headline": "Germany expands nurse recognition program to include more Indian universities", "image": "https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=800", "source": "Bundesagentur für Arbeit", "date": "2026-04-22", "summary": "The Federal Employment Agency has added 12 additional Indian nursing schools to its list of pre-recognized programs, streamlining the Anerkennung process."},
    {"id": "news-3", "category": "UK", "headline": "NMC introduces updated OSCE stations for internationally educated nurses", "image": "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800", "source": "NMC News", "date": "2026-04-15", "summary": "The Nursing and Midwifery Council has revised three OSCE stations to reflect current UK clinical practice, effective June 2026."},
    {"id": "news-4", "category": "Education", "headline": "New study reveals shortage of ICU-trained nurses will double by 2030", "image": "https://images.unsplash.com/photo-1512678080530-7760d81faba6?w=800", "source": "The Lancet", "date": "2026-04-10", "summary": "A global study projects a critical shortage of specialized critical-care nurses, prompting new fast-track certification programs."},
    {"id": "news-5", "category": "Jobs", "headline": "Saudi Arabia announces 15,000 new nursing positions across major hospitals", "image": "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800", "source": "MoH Saudi Arabia", "date": "2026-04-05", "summary": "The Ministry of Health has opened recruitment for 15,000 nurses to support Vision 2030 healthcare expansion."},
]


JOBS = [
    {"id": "job-1", "employer": "Cleveland Clinic Abu Dhabi", "position": "Staff Nurse – ICU", "city": "Abu Dhabi", "country": "UAE", "flag": "🇦🇪", "specialty": "Critical Care", "experience": "2+ years", "salary": "AED 12,000 - 15,000 / month", "shift": "Rotating", "type": "Full-time", "posted": "2 days ago"},
    {"id": "job-2", "employer": "King Faisal Specialist Hospital", "position": "Registered Nurse – Oncology", "city": "Riyadh", "country": "Saudi Arabia", "flag": "🇸🇦", "specialty": "Oncology", "experience": "3+ years", "salary": "SAR 9,000 - 12,000 / month", "shift": "12-hour", "type": "Full-time", "posted": "1 week ago"},
    {"id": "job-3", "employer": "Charité Berlin", "position": "Pflegekraft (Recognition track)", "city": "Berlin", "country": "Germany", "flag": "🇩🇪", "specialty": "Medical-Surgical", "experience": "1+ years", "salary": "€2,800 - 3,400 / month", "shift": "Rotating", "type": "Full-time", "posted": "3 days ago"},
    {"id": "job-4", "employer": "NHS Trust", "position": "Band 5 Nurse – Adult Care", "city": "London", "country": "UK", "flag": "🇬🇧", "specialty": "Adult", "experience": "OSCE-ready", "salary": "£28,407 - £34,581 / year", "shift": "Rotating", "type": "Full-time", "posted": "5 days ago"},
    {"id": "job-5", "employer": "Toronto General Hospital", "position": "RN – Cardiac Care Unit", "city": "Toronto", "country": "Canada", "flag": "🇨🇦", "specialty": "Cardiac", "experience": "2+ years", "salary": "CAD 75,000 - 95,000 / year", "shift": "12-hour", "type": "Full-time", "posted": "1 day ago"},
]
